### ISSUE TITLE
Cannot find name 'HighchartsOptions'

### ISSUE THREAD

**Issue by sballan** [cebor/angular-highcharts#10]
Looks like 'HighchartsOptions' is not in the @types module recommended in the readme.  My charts will render, but I get a series of errors looking like this:

`client:80 [default] /...node_modules/angular-highcharts/src/chart.d.ts:7:13 
Cannot find name 'HighchartsOptions'.`

Any thoughts?

**Comment by cebor** [comment]
Ok seems, that Highcharts has refactored some of the Types:

for now you can use `"@types/highcharts": "4.2.34"` which should work.

I will fix this after the weekend.

**Comment by cebor** [comment]
@sballan 

Should be fixed in `v0.7.0`.

Can you confirm this please?

**Comment by bona1337** [comment]
confirm.
