### ISSUE TITLE
Export button is not displayed

### ISSUE THREAD

**Issue by h0ujun** [cebor/angular-highcharts#100]
I already enabled it in the chart but it is still not showing, any other options I need to add? Thanks!

    this.chart = new Chart({
      chart: {
        type: 'pie',
        backgroundColor:'transparent'
      },
      title: this.data.title,
      tooltip: {
        headerFormat: '',
        pointFormat: '{point.name} : <b>{point.percentage: .2f} %</b><br/>'
      },
      plotOptions: {
        pie: {
          allowPointSelect: true,
          dataLabels: {
            enabled: false,
          },
          slicedOffset: 0,
          showInLegend: true,
          innerSize: '40%',
          shadow: true
        }
      },
      exporting: {
          enabled: true
      },
      credits: {
        enabled: false
      },
      series: [this.data]
    });

**Comment by cebor** [comment]
have you loaded exporting module ?

see: https://github.com/cebor/angular-highcharts#using-highcharts-modules

**Comment by h0ujun** [comment]
Thanks!! Got it!

**Comment by narendralussspacetech** [comment]
@cebor Really happy to use this library. And thanks for it. I'm trying to use this library and working well but I can't able to see `Download Excel` option along with other download option overt charts.

Is there any extra library to enable `Download Excel` option along with others?

Thanks

**Comment by narendralussspacetech** [comment]
@cebor I got it. I've to provide `import * as exportData from 'highcharts/modules/export-data.src';` into provider along with exporting too. Resolved!
