### ISSUE TITLE
SolidGauge exception

### ISSUE THREAD

**Issue by hghammoud** [cebor/angular-highcharts#107]
I m trying to add a solidgauge chart but i m getting a c.init is not a function.

Can you pls tell me what am I doing wrong?

https://stackblitz.com/edit/angular-sucuic

**Comment by cebor** [comment]
@hghammoud you also have to load the following highcharts module: 

```ts
import more from 'highcharts/highcharts-more.src';
```

**Comment by hghammoud** [comment]
Did you even try it? your answer is not complete it doesnt work. After research in other tickets, this is what worked for me will need 

import solidgauge from 'highcharts/modules/solid-gauge.src';
import more from 'highcharts/highcharts-more.src';
import * as Highcharts from 'highcharts';
more(Highcharts);
solidgauge(Highcharts);

**Comment by cebor** [comment]
@hghammoud sure!

See: https://stackblitz.com/edit/angular-vjztwk

**Comment by hghammoud** [comment]
Weird. Ok my bad then. Tnx
