### ISSUE TITLE
How can I use No data to display, I am using angular 4.

### ISSUE THREAD

**Issue by prameetpradhan** [cebor/angular-highcharts#108]

**Comment by prameetpradhan** [comment]
Module definition should be as below.
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';
import noData from 'highcharts/modules/no-data-to-display.src';

import { AppComponent } from './app.component';
export function highchartsModules() {
  // apply Highcharts Modules to this array
  return [ noData ];
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    ChartModule
  ],
  providers: [{ provide: HIGHCHARTS_MODULES, useFactory: highchartsModules }],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by prameetpradhan** [comment]
got solution

**Comment by HankXu** [comment]
@prameetpradhan hi~I also encountered this problem, can you tell me your solution ? thanks！！

**Comment by prameetpradhan** [comment]
@HankXu, what is the issue. Could you share your code.

**Comment by HankXu** [comment]
@prameetpradhan I am confusing how to show a message like "no data to display" when there is no data visible in chart. The official document explain this feature requires the file "no-data-to-display.js" to be loaded in the page, so I import the file in the "index.html", it seems ineffective

**Comment by prameetpradhan** [comment]
@HankXu , try as below
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';
import { ChartComponent } from './chart.component';
import { BarChartComponent } from './bar-chart.component';
import noData from 'highcharts/modules/no-data-to-display.src';

import { AppComponent } from './app.component';
export function highchartsModules() {
  // apply Highcharts Modules to this array
  return [ noData ];
}

@NgModule({
  declarations: [
    AppComponent,
    ChartComponent,
    BarChartComponent
  ],
  imports: [
    BrowserModule,
    ChartModule
  ],
  providers: [{ provide: HIGHCHARTS_MODULES, useFactory: highchartsModules }],
  bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by HankXu** [comment]
@prameetpradhan Thank you so much!!! It works 👍
