### ISSUE TITLE
addPoint() is not working iwth StockChart

### ISSUE THREAD

**Issue by theunreal** [cebor/angular-highcharts#114]
`addPoint is not a function`

with normal chart it works.

doese't work:
`currentChart = new StockChart({series: [{name: 'Price (USD)', data: []}]});`

work:
`currentChart = new Chart({series: [{name: 'Price (USD)', data: []}]});`

**Comment by cebor** [comment]
@theunreal yes correct. addPoint is currently not supported. 

Please use `stockChart.ref`. It's a ref to the official chart object. All methods documented in the highcharts docs should work.
