### ISSUE TITLE
Is boost working in Angular 5 ?

### ISSUE THREAD

**Issue by tpps88206** [cebor/angular-highcharts#115]
Hello
I am using Angular 5.0.0 develop Highchart.
Is boost and boost.js library working on Angular ?

I am drawing 11 line charts in one pages.
The total points is 75,000.
It cost 6-7 seconds to load all charts.
Is it possible improved the performance in 2-3 seconds ?

----

`boost: { useGPUTranslations: true },`

[boost.js](https://www.highcharts.com/blog/news/175-highcharts-performance-boost/)

**Comment by cebor** [comment]
Yes should be loaded as any other highcharts module.

See: https://github.com/cebor/angular-highcharts#using-highcharts-modules
