### ISSUE TITLE
Two-way data binding.

### ISSUE THREAD

**Issue by jarrettj** [cebor/angular-highcharts#116]
Hi,

Good day.

How would one go about updating a series based on a couple of input values?

```
export class TestComponent implements OnInit {
chart: Chart;
input1 = 1;
input2 = 2;
input3 = 3;
...
series: [{
        name: 'Test line',
        data: [input1, input2, input3]
      }]
...
this.chart = chart;
```

My view has:
```
<input [(ngModel)]="input1" >
<input [(ngModel)]="input2" >
<input [(ngModel)]="input3" >
...
<div  #[chart]="chart"></div>
```

Is that even possible? (My angular foo is not that strong:)

Regards.
JJ

**Comment by cebor** [comment]
After changing the values you have to redraw the chart.

https://api.highcharts.com/class-reference/Highcharts.Chart#redraw

To get that working you have to implement a change listener.

```angular
<input [(ngModel)]="input1" (change)="chart.ref.redraw()">
<input [(ngModel)]="input2" (change)="chart.ref.redraw()">
<input [(ngModel)]="input3" (change)="chart.ref.redraw()">
...
<div  #[chart]="chart"></div>
```

**Comment by jarrettj** [comment]
Thanks for the prompt response man! 👍 , I get the following error:

`There is no directive with "exportAs" set to "chart"`

I'll google around, I'm sure it's my lack of angular5 knowledge.

Thanks again.

Regards.
JJ

**Comment by cebor** [comment]
@jarrettj 

Can you try the following?

```html
<input [ngModel]="input" (ngModelChange)="chart.ref.redraw()">
```

**Comment by jarrettj** [comment]
No luck. More on the error:

```
There is no directive with "exportAs" set to "chart" (" {{repayment}}
        </mat-grid-tile-header>
        <div [ERROR ->]#[chart]="chart"></div>
        <!--<div [chart]="getChart()"></div>-->
      </mat-grid-tile>
```

Is that # in front of:
`<div  #[chart]="chart"></div>`

correct?

**Comment by cebor** [comment]
no don't think so.

**Comment by jarrettj** [comment]
Cool man, I'll figure it out later. Will go through the docs step by step again, I must have missed something. Thanks for the help.

**Comment by cebor** [comment]
@jarrettj If you still need help, let me know. Then i will serve you an working example.

Closing this for now.

**Comment by jarrettj** [comment]
Hey,

Just letting you know what eventually worked for me:

```
// Template
<input [(ngModel)]="input1" (change)="redraw()">

// Component
redraw() {
    this.chart.ref.series[0].setData(this.getNew());
    this.chart.ref.redraw();
}

getNew() {
    return [3,2,1];
}
```

That will do. Thanks for the help :) 👍 

Regards.
JJ
