### ISSUE TITLE
Two pie charts in one graph

### ISSUE THREAD

**Issue by dfloriano** [cebor/angular-highcharts#119]
I'm having troubles to put two pie charts in one graph. With the JS API I can use the `center` property on he `series` option like [this](http://jsfiddle.net/Adysone/YpfBs/) example, but with angular I get this message error:

> Object literal may only specify known properties, and 'center' does not exist in type 'IndividualSeriesOptions'.

I'm using like the following exemple above:
```
series: [{
   type: 'pie',
   name: 'Working',
   size: 150,
  center: [100,100],
   data: [{
      name: 'Physician',
      y: 10
   }, {
      name: 'Teacher',
      y: 8
   }]
   }, {
   type: 'pie',
   name: 'Dismiss',
   size: 150,
   center: [300,100],
   data: [{
      name: 'Teacher',
      y: 10
   }, {
   name: 'Doctor',
   y: 4
   }]
}]
```

Seems like that the `center `property doesn't exist, what I can do to make this work?

**Comment by cebor** [comment]
This is a problem with `@types/highcharts`.

As workorung follow the guidelines mentioned in the troubleshooting section: https://github.com/cebor/angular-highcharts#troubleshooting
