### ISSUE TITLE
Directive is disabling side navbar

### ISSUE THREAD

**Issue by ziaulain** [cebor/angular-highcharts#125]
Everything else is working fine. Charts are generated, data is populated but as i add the chart selector in my component side navbar navigation stops working.

**Comment by cebor** [comment]
Can you please provide an example to reproduce this issue.

You can use the following as template: https://stackblitz.com/edit/angular-9nkrgd

**Comment by ziaulain** [comment]
Hi,

I was unable to reproduce the issue.

Here is the link which is working. https://angular-9nkrgd.stackblitz.io

But in my local project the sidebar navigation stops working.
