### ISSUE TITLE
Heat map

### ISSUE THREAD

**Issue by zuzi-troj** [cebor/angular-highcharts#126]
I have exactly the same thing in my project like this demo [https://www.highcharts.com/demo/heatmap](url) 
bat I can not get any labels on axis, can you help me ?
this image is from my projekt
![heatmap](https://user-images.githubusercontent.com/33194799/35520614-cc1754da-0517-11e8-8086-3f92173ef830.jpg)

thanks

**Comment by zuzi-troj** [comment]
I Have it
yAxis: {
 this is the culprit --->  **visible: true,**
        title: {text: 'Title Y' },
        labels: {format: '{value}'},
      },

**Comment by BearandYoon** [comment]
Hi @zuzi-troj 
I am trying to get the same heatmap that you have implemented in your project but I can't do it.
I guess that the main issue is 
```
 colorAxis: {
        min: 0,
        minColor: '#FFFFFF',
        maxColor: Highcharts.getOptions().colors[0]
    },
```

Can you share your codesample here?

**Comment by zuzi-troj** [comment]
import { Chart, MapChart  } from 'angular-highcharts';
import * as highmaps from 'highcharts/modules/map.src';
...
const chart = new MapChart({
...
try this

**Comment by zuzi-troj** [comment]
[my-app.zip](https://github.com/cebor/angular-highcharts/files/2313940/my-app.zip)
