### ISSUE TITLE
show loading

### ISSUE THREAD

**Issue by dfloriano** [cebor/angular-highcharts#127]
I have to wait for a server response to build one chart, so I tried to set the loading state as [**this**](http://jsfiddle.net/QSfEJ/) example but seems that is not a known method. There's another way to make this work or an example of I've should done?

**Comment by cebor** [comment]
This is not implemented in this library wrapper. But you can use the official highcharts api to set the `loading` property.

Example (code not testes):

```ts
// setting directly
this.yourChart.ref.options = opts

// or via method
this.yourChart.ref.update(opts)
```

**Comment by dfloriano** [comment]
`ref` property is `undefined` even if I create a chart under this, like:

`this.mychart = new Chart(<any>{ .. });
 this.myChart.ref.showLoading();`

I'm missing something?

**Comment by cebor** [comment]
ref should be defined in the component where using the `[chart]` directive. In `ngAfterViewInit` LifeCycle hook.
