### ISSUE TITLE
Regression between 5.2.1 and 5.2.6 for StockChart

### ISSUE THREAD

**Issue by transparentech** [cebor/angular-highcharts#130]
Thanks for your work on angular-highcharts!

I was using 5.2.0 successfully with StockChart. I then upgraded to 5.2.7 (no code changes on my side) and my stock charts started looking like simple line charts (x-axis treated as a number, navigator not present, etc).

I downgraded to 5.2.1 and the StockChart worked again. I then upgraded to 5.2.6 and it went back to the simple line chart. So somewhere in version >= 5.2.2 something messed up the StockChart support.

**Comment by transparentech** [comment]
As an example of the issue, I updated the StockChart demo by changing the version of angular-highcharts to 5.2.7:

https://stackblitz.com/edit/angular-highcharts-stock-b2xmxb

It's a fork of your original "angular-highcharts-stock" demo, with just the version of angular-highcharts changed from 5.2.0 to 5.2.7.

**Comment by cebor** [comment]
@transparentech fixed in 5.2.8. Thank you for the indication.
