### ISSUE TITLE
Property 'addSeries' does not exist on type 'ChartObject'.

### ISSUE THREAD

**Issue by transparentech** [cebor/angular-highcharts#131]
With v5.2.8, when calling addSeries() on the chart.ref object, typescript gives the error message, 

`Property 'addSeries' does not exist on type 'ChartObject'.`

From this code:

`this.chart.ref.addSeries({data: myData});`

Where 'this.chart' is defined as:

`chart: StockChart`

v5.2.0 does not have this issue.

I'm using:

"typescript": "~2.5.3"
"@angular/cli": "1.6.7",
"angular-highcharts": "^5.2.0",

**Comment by cebor** [comment]
Currently `StockChart` and `MapChart` does not have an implementation of `prototype.addPoint`etc.

Please use `prototype.ref`
