### ISSUE TITLE
TypeError: chartModule is not a function 

### ISSUE THREAD

**Issue by gubenkovalik** [cebor/angular-highcharts#133]
# FIX THIS SHIT URGENTLY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
TypeError: chartModule is not a function
Stack trace:
ChartService.prototype.initModules/<@webpack-internal:///../../../../angular-highcharts/angular-highcharts.es5.js:305:13
ChartService.prototype.initModules@webpack-internal:///../../../../angular-highcharts/angular-highcharts.es5.js:304:9
ChartModule@webpack-internal:///../../../../angular-highcharts/angular-highcharts.es5.js:326:9
_createClass@webpack-internal:///../../../core/esm5/core.js:11089:20
_createProviderInstance$1@webpack-internal:///../../../core/esm5/core.js:11063:26
initNgModule@webpack-internal:///../../../core/esm5/core.js:11016:28
NgModuleRef_@webpack-internal:///../../../core/esm5/core.js:12271:9
createNgModuleRef@webpack-internal:///../../../core/esm5/core.js:12260:12
NgModuleFactory_.prototype.create@webpack-internal:///../../../core/esm5/core.js:15732:16
PlatformRef.prototype.bootstrapModuleFactory/<@webpack-internal:///../../../core/esm5/core.js:5690:64
ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:388:17
onInvoke@webpack-internal:///../../../core/esm5/core.js:4948:24
ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:387:17
Zone.prototype.run@webpack-internal:///../../../../zone.js/dist/zone.js:138:24
NgZone.prototype.run@webpack-internal:///../../../core/esm5/core.js:4765:54
PlatformRef.prototype.bootstrapModuleFactory@webpack-internal:///../../../core/esm5/core.js:5688:16
PlatformRef.prototype.bootstrapModule/<@webpack-internal:///../../../core/esm5/core.js:5767:53
ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:388:17
Zone.prototype.run@webpack-internal:///../../../../zone.js/dist/zone.js:138:24
scheduleResolveOrReject/<@webpack-internal:///../../../../zone.js/dist/zone.js:858:52
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:421:17
Zone.prototype.runTask@webpack-internal:///../../../../zone.js/dist/zone.js:188:28
drainMicroTaskQueue@webpack-internal:///../../../../zone.js/dist/zone.js:595:25
main.ts:14:18

**Comment by SayakMukhopadhyay** [comment]
No need to be rude mate. You haven't given any details except the stacktrace. Check #112

**Comment by gubenkovalik** [comment]
So then who can tell me why this is not maintained?

**Comment by gubenkovalik** [comment]
U can see all the issues are still opened and no one gives f**k abou it

**Comment by SayakMukhopadhyay** [comment]
There are 18 open issues and 68 closed. Quite healthy I would say. I don't want to get into a war of words here but you should definitely check out #112 .If it doesn't work, post a plnkr, stackblitz or any kind of reproduction.

**Comment by cebor** [comment]
Closed see: https://github.com/cebor/angular-highcharts/issues/112#issuecomment-355059670
