### ISSUE TITLE
SolidGauge chart not working

### ISSUE THREAD

**Issue by naveendb92** [cebor/angular-highcharts#136]
I'm unable to render **solid gauge** chart. Its throws error:
**Error: Highcharts error #17**

@cebor kindly help me.

**Comment by douglasPinheiro** [comment]
https://github.com/cebor/angular-highcharts/issues/113

**Comment by naveendb92** [comment]
Thanks @douglasPinheiro

**Comment by remborg** [comment]
It's old but I just had this issue, you can find a short piece of code in my comment there https://github.com/cebor/angular-highcharts/issues/112 
Hope it helps!
