### ISSUE TITLE
Add/ modify series data on StockCharts

### ISSUE THREAD

**Issue by alekplay** [cebor/angular-highcharts#138]
When trying to either add, remove, or modify the series of a StockChart I get a compilation error saying that the method (`this.chart.addSerie()`, ...) or property (`this.chart.series`) doesn't exist. If I try to mutate `this.chart.options.series` I get a `null` error, and printing the value of `this.chart.options.series` shows that it is null. Is this a known issue? Any fix for this?

**Comment by cebor** [comment]
@alekplay yes this is a known issue. Stock and Mapchart do not have these methods.

But you can use `this.chart.ref` which is a reference to the original highcharts object.
