### ISSUE TITLE
Chart size not getting handled correctly on first load

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [cebor/angular-highcharts#141]
I am trying to implement theme switching. The idea of the theme switch is to dynamically load css files in the header on user action. This is causing an issue where the chart is not sized properly and is exceeding the width of the container. I have been able to reproduce this https://stackblitz.com/edit/clarity-theme-switch-highchart-problem . This might be similar to #6 . The issue is not present when the css is loaded early either due to static html or angular-cli configuration. I believe that timings are off somewhere as it works partially by following https://github.com/cebor/angular-highcharts/issues/6#issuecomment-368943049 along with a timeout
```
ngAfterViewInit(): void {
    setTimeout(() => {
        window.dispatchEvent(new Event('resize'));
    }, 1000);
}
```
But this sometimes does not work on Firefox. Looking for a definite solution or workaround.

**Comment by juanviera89** [comment]
You need to call the chart render after style and html render.  I used this:


`
ngAfterViewInit() {
    // edit 
    this.options = {
      xAxis: { type: 'datetime' },
      yAxis: {
        title: {
          text: 'Influence'
        }
      },
      title: { text: 'Influence trend' },
      series: [{
        type: 'area',
        name: 'USD to EUR',
        data: [
          [Date.UTC(2013, 5, 2), 0.7695],
          [Date.UTC(2013, 5, 3), 0.7648],
          [Date.UTC(2013, 5, 4), 0.7645],
          [Date.UTC(2013, 5, 5), null],
          [Date.UTC(2013, 5, 6), 0.7549],
          [Date.UTC(2013, 5, 9), 0.8900],
          [Date.UTC(2013, 5, 13), 0.8950]
        ]
      },
      {
        type: 'area',
        name: 'USD to EUR',
        data: [
          [Date.UTC(2013, 5, 3), 0.5648],
          [Date.UTC(2013, 5, 4), 0.5645],
          [Date.UTC(2013, 5, 5), 0.5638],
          [Date.UTC(2013, 5, 6), 0.5549],
          [Date.UTC(2013, 5, 8), 0.6900],
          [Date.UTC(2013, 5, 11), 0.6950]
        ]
      }]
    };
    this.chart = new Chart(this.options);
  }
switchTheme() {
    if (this.theme.name === 'light') {
      this.theme = this.themes[1];
    } else {
      this.theme = this.themes[0];
    }
    localStorage.setItem('theme', JSON.stringify(this.theme));
    this.linkRef.href = this.theme.href;

   // edit
    this.chart = new Chart(this.options);
  }`

and the chart is getting the rigth size after changing the theme. Also changed ngOnInit with ngAfterViewInit for the same reason i mentioned.

I apologyze because of my horrible english

**Comment by SayakMukhopadhyay** [comment]
I have tried putting my rendering block inside `ngAfterViewInit` but I am getting the same result. Updated stackblitz https://stackblitz.com/edit/clarity-theme-switch-highchart-problem-1

**Comment by SayakMukhopadhyay** [comment]
So, after careful examination of the html and timings I have understood the root cause of the problem. The theme stylesheet is getting loaded in memory after the view has been initialised i.e. after `ngAfterViewInit` has been fired. This is because although I am loading the stylesheet into the html way ahead (in the constructor), it takes time to download it. In the meantime the view is initialised with no stylesheet. The chart thus takes the full width available and makes its size 33px lesser. When the stylesheet is loaded in memory at last, the chart remains at the width it was.
At this point, what is needed is (imo) a way to know when a particular stylesheet has finished loading or maybe a css hack to force the chart to be inside the container.

**Comment by SayakMukhopadhyay** [comment]
I realised that this is more of an Angular issue than highcharts issue so I asked in SO and got the perfect answer. https://stackoverflow.com/a/49168653/5863472 for reference. Closing issue,
