### ISSUE TITLE
SolidGauge rendering error

### ISSUE THREAD

**Issue by juanviera89** [cebor/angular-highcharts#142]
I am using highchart solid gauge example without title nor icons (https://www.highcharts.com/demo/gauge-activity) in ionic. Used this code for importing 

`import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';
import more from 'highcharts/highcharts-more.src';
import exporting from 'highcharts/modules/exporting.src';
export function highchartsModules() {
  // apply Highcharts Modules to this array
  return [ more, exporting ];
}
 // important ##########################################
import solidgauge from 'highcharts/modules/solid-gauge';
import * as Highcharts from 'highcharts';
more(Highcharts);
solidgauge(Highcharts);
// important ##########################################`

and for rendering 

`ionViewDidLoad() {
    console.log('ionViewDidLoad ConnectPage');
    //console.log(this.serie);
    this.chart11 = new Chart({
      credits: {
          enabled: true
      },
      exporting: {
          enabled: false
      },
      chart: {
          type: 'solidgauge',
          height: '100%'
      },
      colors: ['#F37961', '#42C2CC', '#42C2CC', '#910000', '#1aadce',
      '#492970', '#f28f43', '#77a1e5', '#c42525', '#a6c96a'],
      title: null,
  
      tooltip: {
          borderWidth: 0,
          backgroundColor: 'none',
          shadow: false,
          style: {
              fontSize: '16px'
          },
          pointFormat: '{series.name}<br><span style="font-size:2em; color: {point.color}; font-weight: bold">{point.y}%</span>',
          positioner: function (labelWidth) {
              return {
                  x: (this.chart.chartWidth - labelWidth) / 2,
                  y: (this.chart.plotHeight / 2) + 15
              };
          }
      },
  
      pane: {
          startAngle: 0,
          endAngle: 360,
          background: [{ // Track for Move
              outerRadius: '112%',
              innerRadius: '88%',
              backgroundColor: "rgba(124,181,236,0.3)",
              borderWidth: 0
          }, { // Track for Exercise
              outerRadius: '87%',
              innerRadius: '63%',
              backgroundColor: "rgba(67,67,72,0.3)",
              borderWidth: 0
          }, { // Track for Stand
              outerRadius: '62%',
              innerRadius: '38%',
              backgroundColor: "rgba(144,237,125,0.3)",
              borderWidth: 0
          }]
      },
  
      yAxis: {
          min: 0,
          max: 100,
          lineWidth: 0,
          tickPositions: []
      },
  
      plotOptions: {
          solidgauge: {
              dataLabels: {
                  enabled: false
              },
              linecap: 'round',
              stickyTracking: false,
              rounded: false
          }
      },
  
      series: [{
          data: [{
              color: "#7cb5ec",
              radius: '112%',
              innerRadius: '88%',
              y: 80,
              
          }]
      }, {
          data: [{
              color: "#434348",
              radius: '87%',
              innerRadius: '63%',
              y: 65
          }]
      }, {
          data: [{
              color: "#90ed7d",
              radius: '62%',
              innerRadius: '38%',
              y: 50
          }]
      }]
  
  });
    
  }`

the problem is, when i use rounded linecaps, it seems to translate the center of the render, so the chart is kind of a kid draw. But when i use squared linecaps it renders perfectly. Does someone know anything about this problem? 

screenshots:

https://drive.google.com/open?id=1uXBQKncvcfamYmVzVwpG67psNMmPt9_n
https://drive.google.com/open?id=1s8PXL4GT7kQhvg6gxZwHhSC5aM8kZiHs

**Comment by mina70** [comment]
@juanviera89 

Can you check this code ? 
I am also facing the same issue and it works for me.

`
/*  app.module.ts */

import { ChartModule, HIGHCHARTS_MODULES  } from 'angular-highcharts';
import * as more from 'highcharts/highcharts-more.src';
import * as solidGauge from 'highcharts/modules/solid-gauge.src';

@NgModule({
 imports: [ChartModule],
 exports: [ChartModule],
 providers: [
       {
            provide: HIGHCHARTS_MODULES,
            useFactory: () => [more, solidGauge]
        }
 ]
`

**Comment by juanviera89** [comment]
I moved back to highcharts because this problem and the issues of updating series and points with agular-highcharts, but I found that the problem with rendering rounded linecaps was a memory error that happens in both highcharts and angular-highcharts.
