### ISSUE TITLE
Cannot change StockChart series options

### ISSUE THREAD

**Issue by norbusan** [cebor/angular-highcharts#144]
With
```
chart: StockChart = new StockChart({ ... })
```
I am trying to adjust the series options `pointInterval` and `pointStart`, but 
```
chart.ref.series[0].update
```
does not allow me to set these values, and I get compilation errors
```
 error TS2345: Argument of type '{ pointInterval: number; }' is not assignable to parameter of type 'IndividualSeriesOptions'.
  Object literal may only specify known properties, and 'pointInterval' does not exist in type 'IndividualSeriesOptions'.
```

Any idea how this can be fixed?

Thanks

**Comment by SayakMukhopadhyay** [comment]
Try to remove the type information from your chart object. The type library of Highcharts is not up to date. This is mentioned in the readme https://github.com/cebor/angular-highcharts/blob/master/README.md#troubleshooting

**Comment by Karlito88** [comment]
You have to convert the type of parameters:

```
const option: StockChart = {
pointInterval: { *stuff* }
}
```
and then you can use chart.ref.series[0].update(options)

**Comment by norbusan** [comment]
thanks, I'll try methods.

**Comment by norbusan** [comment]
Hi 
@SayakMukhopadhyay thanks, the solution as mentioned in the readme worked, sorry for not having found it myself.
@Karlito88 That didn't work for me, either.
