### ISSUE TITLE
Where is the addPoint() method in stock chart object?

### ISSUE THREAD

**Issue by yash27** [cebor/angular-highcharts#147]
I am using candlestick stock chart with ohlc values and volume. I have 4 series in my chart, one with ohlc values, one with volume and two are of SMA. Now I want to add points in my ohlc series and volume series. I didn't found any method like `addPoint() ` . If there is any such method or any alternative is there, please reply or answer.

I have the following series mentioned below:

```
series: [{
        type: 'candlestick',
        name: 'E-mini',
        id: 'emini',
        data: this.ohlc,

      }, {
        id: 'sma50',
        type: 'sma',
        linkedTo: 'emini',
        params: {
          period: 5
        }
      }, {
        type: 'sma',
        linkedTo: 'emini',
        params: {
          period: 20
        }
      }, {
        type: 'column',
        name: 'Volume',
        data: this.volume,
        yAxis: 1,

      }]
```

I want to add point after loading the chart using chart object in ohlc candlestick series as well as in volume series. Thank You

Thank you.

**Comment by SayakMukhopadhyay** [comment]
You can find the relevant documentation [here](https://github.com/cebor/angular-highcharts#methods). The important part is getting the `ref` of the chart object. Its important to note that the `ref` property is only available after the `ngAfterViewInit()` hook.
Take a look [here](https://github.com/SayakMukhopadhyay/elitebgs/blob/4c49738ab9fdfc2e357e0786cbb09e7881323a86/src/app/main/charts/faction-state-chart.component.ts) for an implementation of `ref` .

**Comment by yash27** [comment]
@SayakMukhopadhyay Thnx buddy, but I got it that day after 3 hours when I submitted my issue.
In the `Chart` object, directly we have `addPoint(), removePoint(), addSeries()` and `removeSeries()` method but in the `StockChart` object, we have to go through `ref`.

**Comment by speence** [comment]
> @SayakMukhopadhyay Thnx buddy, but I got it that day after 3 hours when I submitted my issue.
> In the `Chart` object, directly we have `addPoint(), removePoint(), addSeries()` and `removeSeries()` method but in the `StockChart` object, we have to go through `ref`.

Any chance you could post a snippet of your code? Ive encountered the same problem, but when I call this.chart.ref.addPoint() I get:
`ERROR TypeError: _this.chart.ref.addPoint is not a function`

**Comment by yash27** [comment]
@speence addPoint() is a method you use to add a point in a series. To access it, you have to select the series where you want to add a point. Suppose you want to add a point in your first series of the chart. 
Code will be like this...

`this.stockChart.ref.series[0].addPoint(point);`

There's no such method like addPoint() in the `chart` or `stockChart` object. You have to mention the series index in which series you want to add a point.

For better results , you can use Observable reference or `ref$` of the chart.

```
this.stockChart.ref$.subscribe(chart=>{

   chart.series[0].addPoint(point);

});
```
