### ISSUE TITLE
ERROR TypeError: __WEBPACK_IMPORTED_MODULE_0_highcharts__.mapChart is not a function

### ISSUE THREAD

**Issue by keshav1007** [cebor/angular-highcharts#150]
I am getting the following error while trying to implement HighMaps

ERROR TypeError: __WEBPACK_IMPORTED_MODULE_0_highcharts__.mapChart is not a function

Can i get some working example of HighMaps?

**Comment by cebor** [comment]
Maybe #112 ?

**Comment by keshav1007** [comment]
@cebor thanks Yea got it.. error gone now after importing as explained.. but the map is empty now.. and the series is null always

**Comment by cebor** [comment]
Ok, maybe overriding the options parameter with `<any>` helps. Typings for highcharts are not very consistent.

**Comment by keshav1007** [comment]
Yes tried that too but still series is coming as null always

**Comment by keshav1007** [comment]
let chartData = [{ code3: "ABW", z: 105 }, { code3: "AFG", z: 35530 }];
        this.chartConfigObject = new MapChart(<any>{
            chart: {
                borderWidth: 1,
                map: 'custom/world'
            },

            title: {
                text: 'World population 2013 by country'
            },

            subtitle: {
                text: 'Demo of Highcharts map with bubbles'
            },

            legend: {
                enabled: false
            },

            mapNavigation: {
                enabled: true,
                buttonOptions: {
                    verticalAlign: 'bottom'
                }
            },

            series: [{
                name: 'Countries',
                color: '#E0E0E0',
                enableMouseTracking: false
            }, {
                type: 'mapbubble',
                name: 'Population 2016',
                joinBy: ['iso-a3', 'code3'],
                data: chartData,
                minSize: 4,
                maxSize: '12%',
                tooltip: {
                    pointFormat: '{point.properties.hc-a2}: {point.z} thousands'
                }
            }]
        });

this is my chartObject

**Comment by cebor** [comment]
see: https://github.com/cebor/angular-highcharts#troubleshooting

**Comment by keshav1007** [comment]
yes i have done the same.. but series is null

**Comment by keshav1007** [comment]
@cebor it would be great if you could help me on this. I have provided the options as <any> only but the series is always null
