### ISSUE TITLE
Highmaps is empty without any errors

### ISSUE THREAD

**Issue by keshav1007** [cebor/angular-highcharts#151]
Hi

Highmaps is coming as empty. I have reproduced here

https://stackblitz.com/edit/angular-highcharts-stock-nbvnuw?file=app%2Fapp.module.ts

What am i missing?  @cebor

**Comment by CollinGraf314** [comment]
I'm pretty sure you're just missing your highcharts dependency. You may have installed angular-highcharts without installing highcharts itself. When I look at your code I see that
