### ISSUE TITLE
Bullet Chart Issue

### ISSUE THREAD

**Issue by sweetyv** [cebor/angular-highcharts#159]
Hi @cebor ,

I am trying to create a Bullet chart of Highcharts in Angular 5. I have managed to create other basic charts but facing issues in Bullet chart. 

app.module.ts
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { ChartModule,HIGHCHARTS_MODULES } from 'angular-highcharts';

import bulletChart from 'highcharts/modules/bullet.src';
import * as Highcharts from 'highcharts';
bulletChart(Highcharts);

import { AppComponent } from './app.component';
import { SimpleChartComponent } from './simple-chart/simple-chart.component';
import { BarChartComponent } from './bar-chart/bar-chart.component';
import { BulletGraphComponent } from './bullet-graph/bullet-graph.component';


@NgModule({
  declarations: [
    AppComponent,
    SimpleChartComponent,
    BarChartComponent,
    BulletGraphComponent
  ],
  imports: [
    BrowserModule, ChartModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

bullet-graph.component.ts
```
import { Component, OnInit } from '@angular/core';
import { Chart } from 'angular-highcharts';

@Component({
  selector: 'app-bullet-graph',
  templateUrl: './bullet-graph.component.html',
  styleUrls: ['./bullet-graph.component.css']
})
export class BulletGraphComponent implements OnInit {
  chart2 = new Chart({
    chart: {
    inverted: true,
    type: 'bullet',
},
title: {
    text: null
},
legend: {
    enabled: false
},

xAxis: {
    gridLineWidth: 1,
    tickWidth: 0,
    labels:{
      enabled: false
    }

        },

credits: {
    enabled: false
},
exporting: {
    enabled: false
},
  series: [{
      data: [{
          y: 28704,
          target: 17997
      }]
  }],

  tooltip: {
      pointFormat: '<b>{point.y}</b> (with target at {point.target})'
  }
  });
  constructor() { }

  ngOnInit() {
  }

}

```

I am getting below error:
Argument of type '{ chart: { inverted: true; type: string; }; title: { text: null; }; legend: { enabled: false; }; ...' is not assignable to parameter of type 'Options'.
  Types of property 'series' are incompatible.
    Type '{ data: { y: number; target: number; }[]; }[]' is not assignable to type 'IndividualSeriesOptions[]'.
      Type '{ data: { y: number; target: number; }[]; }' is not assignable to type 'IndividualSeriesOptions'.
        Types of property 'data' are incompatible.
          Type '{ y: number; target: number; }[]' is not assignable to type '(number | [number, number] | [string, number] | DataPoint)[]'.
            Type '{ y: number; target: number; }' is not assignable to type 'number | [number, number] | [string, number] | DataPoint'.
              Object literal may only specify known properties, and 'target' does not exist in type 'number | [number, number] | [string, number] | DataPoint'.

Could you please help me understand where I am going wrong?

**Comment by kaka2k** [comment]
I am getting exact same error with bubble chart.  Any solution? I am using [HighCharts](https://www.npmjs.com/package/highcharts) from npm with Angular. I have many chart type and they all are working except bubble chart.

**Comment by sweetyv** [comment]
Hi @kaka2k ,

My code started working properly when I changed the below line in app.module.ts file, from 
`import bulletChart from 'highcharts/modules/bullet.src';` to `import * as bulletChart from 'highcharts/modules/bullet';`

Hope this works for you.
