### ISSUE TITLE
Is this library compatible with styled mode?

### ISSUE THREAD

**Issue by Jrubzjeknf** [cebor/angular-highcharts#167]
Hello,

I'd like to use this library with highcharts with [styled mode](https://www.highcharts.com/docs/chart-design-and-style/style-by-css). This means that all the javascript files for highcharts and its modules come from the _highcharts/js/_ directory.

Is this currently possible? If not, could it be made possible?

With kind regards,
Jrubzjeknf

**Comment by CollinGraf314** [comment]
This is some functionality I would really appreciate having as well.

**Comment by httpete** [comment]
Is this still an issue with HC Version 7 ? We really need styledMode.

**Comment by httpete** [comment]
You don't need to load separate files anymore for Highcharts 7, this issue should be closed. The only issue is how to globally configure highcharts options now .
