### ISSUE TITLE
`chart.ref.update()` is not updating options after render

### ISSUE THREAD

**Issue by codelemur** [cebor/angular-highcharts#169]
## Summary
**Expected behavior:**
When I call `chart.ref.update({lang: {noData: 'foobar'}}, true)` I would expect the chart's options to update as well as the noData text displayed.

**Actual behavior:**
`chart.options` and `chart.ref.options` remain unchanged after calling `chart.ref.update`.

<br/>
Not sure if this applies to other properties, so far I've only tested with the `lang.noData` property.
## Reproduction Setup

* node: v8.9.4 LTS
* angular: 5.2.9
* angular-highcharts: 5.2.12
* highcharts: 6.1.0

You can also view it in this demo: [StackBlitz Demo](https://stackblitz.com/edit/angular-highcharts-doesnt-update-nodata)

**Comment by cebor** [comment]
Are you sure this is working with native Highcharts?

I think changing the lang object ist not possible after Highcharts gets initialised for the first time, even with redraw set to true.

FYI: https://api.highcharts.com/highcharts/lang

**Comment by codelemur** [comment]
Interesting, it being loaded only once at the beginning makes sense. I'll close issue. For anyone finding this later, a workaround could be doing the following if you need to update noData message after rendering:

```ts

interface CustomHighchartsObject extends Highcharts.ChartObject {
  hasData(): boolean;
  showNoData( str?: string): void;
  hideNoData(): void;
}

 ngAfterViewChecked() {
    // bail early if we dont have a chart to work with
    if ( !this.chart || !this.chart.ref ) {
      return;
    }
    const ref = this.chart.ref ;

    // hasData definitely exists, please see our README for explanation
    const hasData = (ref as CustomHighchartsObject).hasData();

    // hide the noData message after every check
    // only add the noData message if it is appropriate
    if ( !hasData ) {
      (ref as CustomHighchartsObject).hideNoData();
      (ref as CustomHighchartsObject).showNoData(this.noDataMessage);
    }
  }
```
