### ISSUE TITLE
doDrilldown() function not recognized

### ISSUE THREAD

**Issue by CollinGraf314** [cebor/angular-highcharts#173]
I'm trying to replicate the functionality shown here: http://jsfiddle.net/7ffhfnvv/1/
and here: http://jsfiddle.net/7ffhfnvv/4/

Specifically, I am allowing users to change the type of chart used to display their data, and I want to be able to preserve the drilldown level after the chart is remade. The doDrilldown() function seems to be exactly what I need, however when I try to call `this.chart.ref.series[0].data[0].doDrilldown();` I get an error saying that `property 'doDrilldown'  does not exist on type 'PointObject'`. When I run `console.log(this.chart);` I can see that doDrilldown exists in the objects prototype. 

![image](https://user-images.githubusercontent.com/9330290/39321314-aaa59d26-4954-11e8-9e3d-429c8f4ce387.png)
![image](https://user-images.githubusercontent.com/9330290/39321333-bc20e8e4-4954-11e8-9361-03ebac44fe35.png)

**Comment by CollinGraf314** [comment]
I've been working on this problem a lot and it seems like I simply don't understand 'ref' enough. 
If I call `this.chart.ref.series[0].points` I get a error saying that the property 'points' doesn't exist on type SeriesObject, but when I console.log it, it's defined. Also, `this.chart.ref.series[0].points[0].doDrilldown()` seems like it is actually recognized as a function, but whenever I make that call nothing seems to happen. Then there's `this.chart.ref.series[0].data[0]` which does exist on type SeriesObject, but `this.chart.ref.series[0].data[0].doDrilldown()` is not a defined property on PointObject, but it does show up in the `__proto__:` of a `console.log(this.chart.ref.series[0].data[0]);` output. And just like `this.chart.ref.series[0].points[0].doDrilldown()` I can get this it to work either.

**Comment by yash27** [comment]
@CollinGraf314 Same problem I also occured when I was working over the `ref` object. Many functions and properties of the charts comes after the view is completely loaded. Whatever options are available inside the `ref` object. Except that also many properties are there which came after the view is completely loaded. View in the sense that component completely integrated with html. 

After so long I come up using any keyword. 

In your case, you were trying to access the points inside the series. So you can do that in this way below

`this.chart.(ref as any).series[0].points`

If you are using IntelliJ, VSCode or any other IDE. If you use any keyword over the `ref`, there will be no intellisense in the IDE but it will also solve your problem upto some extent.

**Comment by yash27** [comment]
@CollinGraf314  I hope it helped you
