### ISSUE TITLE
potential race-case with this.chart.ref being defined

### ISSUE THREAD

**Issue by CollinGraf314** [cebor/angular-highcharts#175]
After calling `this.chart = new Chart(myOptions);`
this.chart.ref will not get set until change detection occurs this.chart (it gets set in ngOnChanges). This means that trying to do any manipulations of the chart right after it is defined will fail. In my case I am trying to drilldown the chart to pick up where my user left off in the drilldown structure of the chart, but I cannot do this without using a setTimeout function. 

```
this.chart = new Chart(myOptions);
console.log(this.chart.ref); // prints undefined
setTimeout(() => {
     console.log(this.chart.ref); // prints a.Chart { ... } as expected
}, 100);
```

**Comment by CollinGraf314** [comment]
I'm coming across this problem after the DOM has already been rendered. I allow my users to change how they want their data displayed, and if they choose to view a bar chart as a column chart, I rebuild the chart with changed chart type. This all works properly, but the added functionality I want is to allow drilldowns to persist across chart type changes. So if a user drills down into a bar chart, then decides they want to see it as a pie chart, they don't get kicked back up to the top level of the chart. This means that in the same function I use to rebuild the chart, I want to use to programatically drilldown into that chart, which I don't believe I can do without this.chart.ref being defined.

Now it's entirely possible I've been going about this the wrong way, so if you know of any better way to get this functionality I'd be glad to hear your suggestions.

**Comment by cebor** [comment]
@CollinGraf314 

In Version 6 you can try to use `ref$`as subscribable observer.

Example:

```ts
chart.ref$.subscribe(chartRef => {
  console.log(chartRef);
})
```

**Comment by CollinGraf314** [comment]
Oh that's awesome. Thanks a bunch!
