### ISSUE TITLE
showing abbreviated values in tooltip

### ISSUE THREAD

**Issue by yash27** [cebor/angular-highcharts#178]
In my component, one method is there which I'm using to get the abbreviated value. Abbreviated value something like if 35100 is there then it will return 35.1k. Following is the method:

```
SI_prefixes : any = ["", "k", "M", "G", "T", "P", "E"];

abbreviateNumber(number){
    var tier = Math.log10(number) / 3 | 0;
    if(tier == 0) return number;
    var prefix = this.SI_prefixes[tier];
    var scale = Math.pow(10, tier * 3);
    var scaled = number / scale;
    return scaled.toFixed(1) + prefix;
}
```

How to use this method in the tooltip formatter so that I will see the abbreviated values in the tooltip.

**Comment by KifayatMsd** [comment]
Solved .... The problem is with `this `keyword which does not represent the component you are in but points to the event raised by hovering over the bar ( in case of bar chart ).
So just initialize the component referencing `this` somewhere outside the highchart object, like below.

```
      let parent = this;
      
      chartConfig = {
        chart: {
          type: 'bar'
        },
        tooltip: {
          formatter: function () {
            var abbrValue = parent.abbreviateNumber(this.y);
            var title = this.x + '<br>';
            var body = '<span style="color:' + this.color + '">●</span>' + this.series.name + '<b>'+ abbrValue + ' </b><br/>';

            return title + body;
          } 
        }
      };
```
