### ISSUE TITLE
stock chart doesn't work in angular 6 but "basic" chart works

### ISSUE THREAD

**Issue by alexanderPastornicky** [cebor/angular-highcharts#183]
Angular CLI: 6.0.3
Node: 8.10.0
OS: linux x64
Angular: 6.0.2

It always renders empty chart (as you can see in image below) even if StockChart options object is identical to options from working example app which is mentioned in your docs.

![screenshot from 2018-05-22 19-36-38](https://user-images.githubusercontent.com/2699816/40380998-d7a72528-5dfa-11e8-8daf-7d37121e4326.png)

**Comment by FilipLukac** [comment]
Same here

**Comment by SoulOnFire** [comment]
Same here

**Comment by cebor** [comment]
fixed in 6.1.4
