### ISSUE TITLE
can't get a "polar" chart

### ISSUE THREAD

**Issue by mig-visiblee** [cebor/angular-highcharts#189]
Hi, we're trying hard to get a polar (spider) chart based on the example in your README.md, using these options, without any success so far...
(using @ types/highcharts 5.0.22, highcharts 6.1.0, angular-highcharts 4.1.2)...

```
this.chart = new Chart({
	chart: {
		polar: true,
		type: 'line'
	},
	title: {
		text: ''
	},
	xAxis: {
		categories: ['#age', '#carrots', '#lime', 'time spent', '#apples'],
		tickmarkPlacement: 'on',
		lineWidth: 1
	},
	credits: {
		enabled: false
	},
	series: [
		{
			type: 'column',
			data: [100, 40, 10, 65, 30]
		}
	]
});
```

--> We get a standard bar chart instead.

Is there something else we should do?

**Comment by mig-visiblee** [comment]
![image](https://user-images.githubusercontent.com/40243343/41401831-1ef7c8a6-6fc1-11e8-8802-01e6e217d349.png)
When logging this.chart.ref, we DO get  `polar: true`... Could it be an issue with HighCharts itself?

**Comment by mig-visiblee** [comment]
It can actually be reproduced by starting off with a sample from HighCharts here (https://jsfiddle.net/1r2fyh8c/3/) and pasting the options to (https://stackblitz.com/edit/angular-9nkrgd). We don't get a polar chart...

**Comment by cebor** [comment]
You have to load the highcharts more module.

**Comment by mig-visiblee** [comment]
Thank you.
I appreciate this is probably beyond 'angular-highcharts', but I'm yet to find how to do this explicitly --
highcharts-more being now included in 'highcharts' npm module, I was assuming it would load automatically... Anyway, we have a workaround using another library, and if we find how to do this I'll post here.
