### ISSUE TITLE
Adding custom buttons throws unnecessary error

### ISSUE THREAD

**Issue by jacobmichaelis** [cebor/angular-highcharts#191]
**Setup:**
Angular 2
Visual Studio Code
Angular-Highcharts

**Goal:**
Add a custom button to the chart, next to the dropdown toggle. I have seen it before so I know it's possible.

**Problem:**
I was actually able to achieve my goal. I created a button that runs a function when clicked.
![image](https://user-images.githubusercontent.com/20326888/41475688-a8afdb0e-707c-11e8-92de-64cdf1af6f2f.png)
![image](https://user-images.githubusercontent.com/20326888/41475704-b6a98fde-707c-11e8-806c-823cd8ddaae4.png)
The problem I'm facing is all of the error messages. 
![image](https://user-images.githubusercontent.com/20326888/41475762-db477374-707c-11e8-90e1-ea06470206da.png)
I don't know how I am compiling and using error-ed out code. I love using the Highcharts library:
```
import { Chart, Highcharts } from 'angular-highcharts';
...
chart: Chart;
options: Highcharts.Options;
```
but to get these errors to go away I have to use `options: any` and then it doesn't give any tooltip help, which I love:
![image](https://user-images.githubusercontent.com/20326888/41476211-1dcaa51c-707e-11e8-94ef-f09ca7cb3375.png)
And I love being able to hit F12 and see the members of each item:
![screenshot 24](https://user-images.githubusercontent.com/20326888/41476618-597e66a6-707f-11e8-9244-093993a761a8.png)
![image](https://user-images.githubusercontent.com/20326888/41476654-7426419a-707f-11e8-8646-f697ccbfb5e2.png)
![image](https://user-images.githubusercontent.com/20326888/41476714-975ad48c-707f-11e8-884f-eb2c5960a917.png)
(Sorry for all the pictures, but using Highcharts without these features is hard, and I want y'all to see how useful it all is.)

**Proposed solution:**
Please consider updating the `interface ExportingOptions` so that `buttons?` isn't confined to only `contextButton?: ExportingContextButton;` but can also allow other custom buttons, which it somehow does anyway.

**Comment by cebor** [comment]
Typing errors can be easily fixed by overwriting the options type as described in the troubleshooting section.

https://github.com/cebor/angular-highcharts#troubleshooting
