### ISSUE TITLE
node_modules/@types/highcharts/modules/drilldown"' has no default export.

### ISSUE THREAD

**Issue by Betoxzx** [cebor/angular-highcharts#195]
**I update angular-higcharts and show me this error**

ERROR in src/app/core/body/dashboard/dashboard.module.ts(13,8): error TS1192: Module '"/home/NubeSicar/node_modules/@types/highcharts/modules/drilldown"' has no default export.

**Comment by hakimio** [comment]
This has nothing to do with this wrapper. Create a bug report in "DefinitelyTyped" github repo.
