### ISSUE TITLE
Access HighchartsChartObject from controller?

### ISSUE THREAD

**Issue by bona1337** [cebor/angular-highcharts#2]
Hey there, 

i'm trying to figure out how to access the methods like reflow or setSize from controller. 
In regular javascript it was always just like get the div element (#somechart).highcharts().reflow()...  As mentioned in the example I'd suggest I should do something like this.chart.reflow but none of them works. I have my charts wrapped in angular2 grid and as soon as the size of the widget changed the chart needs to be rerendered.

hope anyone can help out.

cheers

**Comment by cebor** [comment]
Sorry it's not well documented yet:

Use `chart.ref.reflow()` where `chart instanceof Chart`

the `ref` is available after the first init.

**Comment by cebor** [comment]
Just updated the README a little bit.

**Comment by bona1337** [comment]
thanks thats it! 👍
