### ISSUE TITLE
 error TS2341 - Angular 6

### ISSUE THREAD

**Issue by malikfaizanhaider** [cebor/angular-highcharts#201]
error TS2341: Property 'options' is private and only accessible within class 'Chart'.

**Comment by cebor** [comment]
Yes, `options` is a private property of `Chart` and shouldn't manipulated by user in anyway. It was set to public accidentally before.

Always create a `new Chart(options)` or use `chart.ref$` to access chart.

**Comment by malikfaizanhaider** [comment]
Thanks.

**Comment by shruHosgowd** [comment]
I also face the same issue. 

I want to change yAaxis min and max dynamically. 

I tried above solution to use chart.ref

this.chart.ref.yAxis.min =10;

ERROR
Error: Cannot read property 'yAxis' of undefined

PLease help me on this.
