### ISSUE TITLE
Trouble in installing group-category module of highchart plugin 

### ISSUE THREAD

**Issue by vikkylu** [cebor/angular-highcharts#208]
Hello There,

I am having trouble in installing group - category module of highchart plugin 
I am following below link 👍  https://libraries.io/npm/highcharts-grouped-categories

Receiving below error:

PS E:\xxxx\xxxx\Source Code\xxxx\xxxx> npm install highcharts-grouped-categories@1.1.2
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/highcharts-grouped-categories failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org:443

Please provide me some way to fix it.

Thank you in advance,
Vikram

**Comment by cebor** [comment]
Please open an issue in the proper repository: https://github.com/blacklabel/grouped_categories/issues
