### ISSUE TITLE
Options sent to highstock candlestick chart not correct

### ISSUE THREAD

**Issue by cuellarTpal** [cebor/angular-highcharts#210]
`var dummie = [[1530570000, 0.96865, 0.96872, 0.96803, 0.96816],
                            [1530570000, 0.96865, 0.96872, 0.96803, 0.96816],
                            [1530570000, 0.96865, 0.96872, 0.96803, 0.96816],
                            [1530570000, 0.96865, 0.96872, 0.96803, 0.96816],
                            [1530570000, 0.96865, 0.96872, 0.96803, 0.96816]]

              
            var options = {
                chart: {
                  backgroundColor: '#f4f4f4',
                  events: {
                    load: function () {
                      this.xAxis[0].setExtremes(data[data.length - 60][0], data[data.length - 1][0]);
                    },
                  },
                  resetZoomButton: {
                    theme: {
                      display: 'none'
                    }
                  }
                },
                xAxis: {
                  type: 'datetime',
                  labels: {
                    format: '{value:%e %b}<br>{value:%k:%M}',
                  }
                },
                yAxis: {
                  opposite: false,
                },
                title: {
                  text: '',
                },
                credits: {
                  enabled: false
                },
                legend: {
                  enabled: false
                },
                navigation: {
                  buttonOptions: {
                    enabled: true
                  }
                },
                tooltip: {
                  enabled: false
                },
                navigator: {
                  adaptToUpdatedData: true,
                  enabled: true,
                  series: {
                    color: '#31b3a4',
                    lineWidth: 1
                  }
                },
                rangeSelector: {
                  selected: 1
                },
                scrollbar: {
                  enabled: false
                },
                series: [{
                  type: 'candlestick',
                  name: 'AAPL Stock Price',
                  data: dummie,
                  dataGrouping: {
                    enabled: true
                  }
                }]
            }`

I am sending the options as stated by highcharts and I'm getting an error
<img width="345" alt="captura de pantalla 2018-08-01 a la s 10 10 20" src="https://user-images.githubusercontent.com/36898520/43530417-1fa74c5e-9573-11e8-8a68-b8ba66a39c28.png">

<img width="1709" alt="captura de pantalla 2018-08-01 a la s 10 09 57" src="https://user-images.githubusercontent.com/36898520/43530428-267239fe-9573-11e8-8fc2-eec2c8cc9a7a.png">

Could you give me an example of what format is required in the options attribute of a candlestick chart please.

**Comment by cebor** [comment]
Highcharts typings are very inconsistent particularly the stock types, so you have to override the options type with `any`.

See: https://github.com/cebor/angular-highcharts#troubleshooting
