### ISSUE TITLE
Property 'SVGRenderer' does not exist on type 'Static'

### ISSUE THREAD

**Issue by sowmya-alugubelli** [cebor/angular-highcharts#211]
Hi,
I'm trying to make a custom symbol using SVGRenderer as below

`    getGraph(pattern, data, xAxis, title, chartType, lineWidth, lineWidthPlus, stacking, compName, threshold?: Array<any>) {
        let series = [];
        Highcharts.SVGRenderer.prototype.symbols.cross = function (x, y, w, h) {
            return ['M', x, y, 'L', x + w, y + h, 'M', x + w, y, 'L', x, y + h, 'z'];
        };
        if (Highcharts.VMLRenderer) {
            Highcharts.VMLRenderer.prototype.symbols.cross = Highcharts.SVGRenderer.prototype.symbols.cross;
        }
        let seriesData: {
            name: string,
            data: Array<any>,
            dataLabels: Object,
            color?: string,
            stacking?: string,`

error:
![image](https://user-images.githubusercontent.com/32380182/43777183-0e4b4cce-9a20-11e8-93f6-1bf6ccf30951.png)

**Comment by cebor** [comment]
Its a typing error. Types for Highcharts are very inconsistent. But there is nothing i can do, just ignore the redlines or override the type with `any`.

**Comment by sowmya-alugubelli** [comment]
Thanks for the answer, done as suggested.
