### ISSUE TITLE
Lang-Options doesn't change Date-Labels

### ISSUE THREAD

**Issue by PeterHueer** [cebor/angular-highcharts#228]
`      lang: {
        decimalPoint: ',',
        thousandsSep: '.',
        loading: 'Daten werden geladen...',
        months: ['Januar', 'Februar', 'März', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Dezember'],
        weekdays: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
        shortMonths: ['Jan', 'Feb', 'Mär', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez'],
        downloadPNG: 'Download als PNG-Bild',
        downloadJPEG: 'Download als JPEG-Bild',
        downloadPDF: 'Download als PDF-Dokument',
        downloadSVG: 'Download als SVG-Bild',
        resetZoom: 'Zoom zurücksetzen',
        resetZoomTitle: 'Zoom zurücksetzen'
      },`

The translation into german doesn't change the X-Axis Labels... It's still in english.

**Comment by cebor** [comment]
Have you used `Highcharts.setOptions({})` to set options?

**Comment by cebor** [comment]
https://api.highcharts.com/highcharts/lang

**Comment by PeterHueer** [comment]
Yes, it works with `Highcharts.setOptions({})` but why i can give the Chart-Constructur an Options-Object with an LangObject? This has no impact on the Datetime labels.

**Comment by cebor** [comment]
See the docs: https://api.highcharts.com/highcharts/

Highcharts does not support `lang` in the `Chart` options, must be typing issue.
