### ISSUE TITLE
ERROR in ChartModule is not an NgModule

### ISSUE THREAD

**Issue by Yooke** [cebor/angular-highcharts#23]
I use the angular-cli@v1.0.0-beta.24, when execute ng server, the console print _ERROR in ChartModule is not an NgModule_, but is can use in browser.
![image](https://cloud.githubusercontent.com/assets/10863906/21374292/acd3cf40-c760-11e6-9469-2de825527cbb.png)

and when execute ng build --aot is have an error 
![image](https://cloud.githubusercontent.com/assets/10863906/21379778/5e75ae10-c78b-11e6-86b7-c6cd41e29e77.png)

**Comment by cebor** [comment]
ok, thanks for the info. don't know if i have time to fix this before xmass ...

**Comment by cebor** [comment]
Just released, a new version.

Can you please test if this fixes the issues for you?

**Comment by Yooke** [comment]
Ok, please wait

**Comment by Yooke** [comment]
good, worked perfectly!

**Comment by cebor** [comment]
nice!
