### ISSUE TITLE
polar=true doesn't work

### ISSUE THREAD

**Issue by shdehnavi** [cebor/angular-highcharts#230]
hi, i wanna draw polar charts and i have a problem with highcharts.
in angular and chart section of chart options, `polar = true` doesn't work and chart displays like a bar and column chart, when i want to draw any charts that used `polar = true` i have this issue.

what's the solution ?

**Comment by cebor** [comment]
Do you have imported the correct additional modules?

**Comment by shdehnavi** [comment]
i've got my answer [here](https://github.com/highcharts/highcharts-angular/issues/82#issuecomment-432530772)

Thank you
