### ISSUE TITLE
Highcharts 7 support

### ISSUE THREAD

**Issue by attilacsanyi** [cebor/angular-highcharts#250]
*“Highcharts 7 is the first release with support for TypeScript through declarations files….“*
https://www.highcharts.com/docs/advanced-chart-features/typescript

**Comment by SayakMukhopadhyay** [comment]
Hopefully they have all the types in use. The Definitely Typed library was lacking in many ways.

**Comment by attilacsanyi** [comment]
Yepp much more types available @SayakMukhopadhyay but as they mentioned there are differences between the Definitely Typed library and in the new types and might be missing once due to beta.

**Comment by cebor** [comment]
i working on it =)

**Comment by attilacsanyi** [comment]
Appreciate @cebor! 👌

**Comment by cebor** [comment]
When this issue https://github.com/highcharts/highcharts/issues/9750 has been fixed, i can release a new version with highcharts 7 support.

**Comment by SayakMukhopadhyay** [comment]
https://github.com/highcharts/highcharts/issues/9750 has been closed for being duplicate to https://github.com/highcharts/highcharts/issues/9705 . Track this instead.

**Comment by KacperMadej** [comment]
FYI: The Highcharts issue will be resolved in 7.0.2 and that version should be published within next few days.

@cebor In general if you want to access a pre-release (e.i. to check code before official release) - let me know how I could help you or what files are needed. You could also open an issue on the Highcharts GitHub with related request for the access.

**Comment by SayakMukhopadhyay** [comment]
7.0.2 has been released.

**Comment by cebor** [comment]
just released 7.1.0 with highcharts 7 support.

**Comment by attilacsanyi** [comment]
Thanks for the **fast adaption @cebor nice work**! I am looking forward to try it.
