### ISSUE TITLE
Property 'type' is missing in type '{ name: string; data: any[]; }'

### ISSUE THREAD

**Issue by troncomputers** [cebor/angular-highcharts#256]
Hi!
I have a problem with Highcharts. Even with an example:
```javascript
const c = new Chart({
  chart: {
   type: 'pie'
   },
    title: {
      text: 'TEST'
    },
    series: [
      {
         name: 'test',
         data: [1, 2, 3, 4, 5, 6]
      }
    ]
});
```
Visual Studio Code highlights `series` section with error:
`Property 'type' is missing in type '{ name: string; data: number[]; }' but required in type 'SeriesXrangeOptions'`.
I can't do `ng serve` because of compilation errors. What am I doing wrong?

**Comment by cebor** [comment]
this issue comes with the new highcharts 7, please open an issue there.

**Comment by web-felicons** [comment]
> Workaround that works for me:
> 
> ```js
> const c = new Chart({
>   chart: {
>    type: 'pie'
>    },
>     title: {
>       text: 'TEST'
>     },
>     series: [
>       {
>          name: 'test',
>          data: [1, 2, 3, 4, 5, 6],
>          type: undefined
>       }
>     ]
> });
> ```
> 
> You have to declare a type of series. Now everything works fine.

I can confirm this workaround works!

**Comment by Dacomis** [comment]
> Workaround that works for me:
> 
> ```js
> const c = new Chart({
>   chart: {
>    type: 'pie'
>    },
>     title: {
>       text: 'TEST'
>     },
>     series: [
>       {
>          name: 'test',
>          data: [1, 2, 3, 4, 5, 6],
>          type: undefined
>       }
>     ]
> });
> ```
> 
> You have to declare a type of series. Now everything works fine.

Can confirm, it works

**Comment by haroon786** [comment]
> ```js
> type: undefined
> ```

what's meaning of type: undefined

**Comment by troncomputers** [comment]
Apparently it's "required" in `serie` object, but I didn't need to specify a type so I put `undefined`. If I remember correctly, `null` doesn't work either. 

BTW
It should be automatically `undefined` if you don't specify any type.
```javascript
    series: [
      {
         name: 'test',
         data: [1, 2, 3, 4, 5, 6]
      }
```
This should work like my workaround.

**Comment by Blindpupil** [comment]
For someone coming later. The proposed solution didn't work for me.
This is what worked for me: 
```
const series =  [
      {
         name: 'test',
         data: [1, 2, 3, 4, 5, 6],
      }
] as SeriesColumnOptions[] // <== or whatever series options you're using

const c = new Chart({
  chart: {
   type: 'pie'
   },
   title: {
      text: 'TEST'
   },
   series,
});
```
