### ISSUE TITLE
Proper way to set Global setOptions in version 7?

### ISSUE THREAD

**Issue by httpete** [cebor/angular-highcharts#266]
The global export of Highcharts has been removed in the latest version. What is the proper way to call setOptions on the global highcharts object now?

**Comment by cebor** [comment]
You can just import from highcharts library.

```ts
import * as Highcharts from 'highcharts';
```

**Comment by httpete** [comment]
OK thanks Cebor, this is something most large apps will need, and the doc would help to show this very common need.

**Comment by AmruthPillai** [comment]
```ts
import * as Highcharts from 'highcharts';
```

This throws an error saying `highcharts` module not found, even though angular-highcharts is working and it exists in my package.json.

**Comment by yubinchen18** [comment]
Hi, 

So I've tried to setOptions for highcharts globally. By doing the following in the app.component.ts

import * as Highcharts from 'highcharts';

constructor() {
    Highcharts.setOptions({
            lang: {
                decimalPoint: ',',
                thousandsSep: '.'
            }
        });
}


But this setting is not 'remembered' in the rest of the application, whenever we do 

new Chart({}) in a component, the set options is forgotten.

So how do we do this globally?

**Comment by mrsegen** [comment]
@cebor Is there a way to do this?
