### ISSUE TITLE
Compiling with --prod and Angular 7.2.5, charts disappear

### ISSUE THREAD

**Issue by httpete** [cebor/angular-highcharts#271]
If I run Angular CLI in normal >npm start mode, it works great. If I build with --prod and deploy, charts are just gone all  I see is  where the chart should be . If I publish with --prod=false, it works fine.

**Comment by httpete** [comment]
we see it's related to aot and buildOptimizer settings. If I turn those off, it works fine.

**Comment by httpete** [comment]
the cheap way to see this is to do >npm run serve -- --prod

**Comment by cebor** [comment]
@httpete i just released an new version compiled with the actual angular-compiler. can you try if its working with this version.

**Comment by httpete** [comment]
Unfortunately @cebor it's the same.  The charts are just gone with aot mode on.

**Comment by cebor** [comment]
ok, its not reproducible for me. Please create an repo or something else to make this reproducible for me.

**Comment by httpete** [comment]
I believe I found it. I am developing a library via npm links, locally disted. Many libraries struggle with this, but they cough up an error that will most likely lead you to this solution.  Angular-highcharts just comes up blank, and doesn't throw the error.

If you develop a shared library and use an npm link, you will need this in the parent project's tconfig.

`
paths: {
      "angular-highcharts": [
        "node_modules/angular-highcharts"
      ]
}

`
