### ISSUE TITLE
Chart options cannot be changed

### ISSUE THREAD

**Issue by thegoodsoldier** [cebor/angular-highcharts#272]
It seems to be impossible to change chart options with the new `ref$` observable.
In a previous version it was possible to change e.g. the xAxis type after the chart has been initialized:
`chart.options.xAxis['type'] = 'datetime';`

With the new version the following doesn't work:
`chart.ref$.subscribe(c => {
    c.options.xAxis['type'] = 'datetime';
});`

Is there a workaround or how can one change the chart options?

**Comment by cebor** [comment]
try to use: https://api.highcharts.com/highcharts/chart.events.redraw
