### ISSUE TITLE
howto: implement stock chart

### ISSUE THREAD

**Issue by wilson0506** [cebor/angular-highcharts#291]
Hi, 
Do you have demo to implement the following chart in angular?
https://www.highcharts.com/stock/demo/sma-volume-by-price

https://www.highcharts.com/stock/demo/stock-tools-custom-gui

Cheers,
Wilson

**Comment by cebor** [comment]
Hi @wilson0506,

https://github.com/cebor/angular-highcharts#highstock--highmaps-support
