### ISSUE TITLE
Create Highcharts on the fly?

### ISSUE THREAD

**Issue by BBlume** [cebor/angular-highcharts#3]
hello
is there a possibility to do something like this in angular2 too?
http://pablojim.github.io/highcharts-ng/examples/example.html
I have a form where i enter some data, I always redraw the chart when a value is changed... sorry new to angular2...

**Comment by cebor** [comment]
You can add Series and Points on the fly via `addPoint` and `addSerie`

The `Chart` constructor accepts the offical `HighchartsOptions`, so your free to use what ever you want.
http://api.highcharts.com/highcharts

And via `chart.ref` you have access to the `HighchartsChartObject`, here you can change aht ever you want.
http://api.highcharts.com/highcharts#Chart

**Comment by cebor** [comment]
i the next days, i will add some functions like, deleteSeries
