### ISSUE TITLE
getSGV method is not available in angular-highcharts

### ISSUE THREAD

**Issue by chandanamadu** [cebor/angular-highcharts#308]
The "getSVG" method is missing from angular-highcharts which is available in the Highchart
Please refer the attached package.json as well.

[highcharts-api](https://api.highcharts.com/class-reference/Highcharts.Chart#getSVG)

![image](https://user-images.githubusercontent.com/9349781/61110083-0b23d400-a4a4-11e9-801e-583b29f840bd.png)

**Comment by cebor** [comment]
@chandanamadu you can call all highcharts methods via the `$ref` observable. Its a direct refference to the original Highcharts Chart object.

See: https://github.com/cebor/angular-highcharts#chart
