### ISSUE TITLE
Compilation Errors in angular 9 

### ISSUE THREAD

**Issue by Bansi23** [cebor/angular-highcharts#326]
![image](https://user-images.githubusercontent.com/51395132/74820127-7893bf00-5327-11ea-8826-0d0b1b2cecc1.png)

get error when complied has  ->no exported member 'ChartObject'. when use angular 9.0.1

 **"highcharts": "^8.0.0",
 "highcharts-angular": "^2.4.0",
 "@angular/core": "^9.0.1",
 "@types/highcharts": "^7.0.0",**

**Comment by cebor** [comment]
Hi @Bansi23, docs were wrong, it should be typed as `Highcharts.Chart`.
