### ISSUE TITLE
chart.destroy() after "Download Image" leads to "ERROR TypeError: Cannot read property 'forExport' of undefined"

### ISSUE THREAD

**Issue by joachimbutz** [cebor/angular-highcharts#330]
I made a minimal example to reproduce the problem: https://github.com/joachimbutz/ng-hc-export-destroy (I could not make the example work in stackblitz unfortunately)

Steps to reproduce:
- In the exporting menu choose a download action (e.g. Download PNG Image)
- Call chart.destroy(), e.g. in the above example via button "Destroy"

The error shown in the console is:
ERROR TypeError: Cannot read property 'forExport' of undefined
    at d.Chart.destroy (highcharts.js:315)
    at Chart.destroy (angular-highcharts.js:112)
    at AppComponent.destroyChart (app.component.ts:48)
    ...

**Comment by cebor** [comment]
should be fixed now!
