### ISSUE TITLE
How to create Sankey Chart using angular-highchart?

### ISSUE THREAD

**Issue by digish777** [cebor/angular-highcharts#333]
If possible,
Please show how to import and use Sankey module.

possibly a Stackblitz Example.

**Comment by digish777** [comment]
found the solution. 
import { Chart } from 'angular-highcharts';
import * as Highcharts from 'highcharts';
import Sankey from "../../../../../../../../../../PROJECT/node_modules/highcharts/modules/sankey";
Sankey(Highcharts);

**Comment by cebor** [comment]
Should also work, as described here:

https://github.com/cebor/angular-highcharts#using-highcharts-modules
