### ISSUE TITLE
Question:  HighStock + Highcharts Modules

### ISSUE THREAD

**Issue by Newan** [cebor/angular-highcharts#34]
Hello,
is it possible to use  HighStock and  Highcharts Modules like Exporting?

thanks

**Comment by cebor** [comment]
This should help you:
https://github.com/cebor/angular-highcharts#using-highcharts-moduleshttps://github.com/cebor/angular-highcharts#using-highcharts-modules

**Comment by cebor** [comment]
I will release Highstocks and Highmaps support with the release of angular 4.

**Comment by Newan** [comment]
thanks!

**Comment by davidmontgom** [comment]
When will Highstocks be available for ang 4.0.x?

**Comment by Darshan-Kushalappa** [comment]
By when can we expect the support for Highstocks and Highmaps?

**Comment by cebor** [comment]
Hi all, im very busy atm, but i will inform you here when its done.

What you can do for now is, to extend the Highcharts module: https://github.com/cebor/angular-highcharts#using-highcharts-modules

```ts
import { Highcharts } from 'angular-highcharts';
require('highcharts/highstock')(Highcharts);
```

**Comment by velusgautam** [comment]
How to use Exporting in Anuglar4

**Comment by cebor** [comment]
@velusgautam 

```typescript
import { Highcharts } from 'angular-highcharts';
require('highcharts/modules/exporting')(Highcharts);
```

**Comment by velusgautam** [comment]
I seen that But Can I use it like this in Component.. Where I can add this in AngularCLI version

**Comment by cebor** [comment]
main.ts should work.

**Comment by ramden** [comment]
Trying the same here. 
I don't get it ... should this 2 lines:

```
import { Highcharts } from 'angular-highcharts';
require('highcharts/highstock')(Highcharts);
```
be somewhere in app.module.ts?

An example would be great where and how exactly to put those values and how to use them in the component

**Comment by cebor** [comment]
@ramden 

Yes app.module.ts is a great place to put these lines.

But Highstocks is not fully supported jet.

**Comment by Hulva** [comment]
I'm doing it [that way](https://github.com/Hulva/AngularDemos/blob/master/about-using-thirdparty-lib/README.md)  to use highchart, i've tried Highstocks, work for me! Before it is available for ang 4.0.x, hope that'll be help.

**Comment by cebor** [comment]
@Hulva Good Catch, i will do some tests, an update the readme accordingly.

**Comment by cebor** [comment]
Seems that `@types/highcharts` have no definitions for modules besides highcharts-more.

**Comment by cebor** [comment]
Using the src files directly should work without typings or declarations:

Example:
```typescript
import { Highcharts } from 'angular-highcharts';
import * as exporting from 'highcharts/modules/exporting.src.js';
exporting(Highcharts);
```

**Comment by epot** [comment]
Just out of curiosity, is the Hightstocks availability is planned in the near future? I am anxious to play with it :).

**Comment by cebor** [comment]
@epot yes you can extend highcharts with highstocks

see: https://github.com/cebor/angular-highcharts#using-highcharts-modules

Example:
```typescript
// app.module.ts
import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';
import Highstock from 'highcharts/highstock.src';

export function highchartsModules() {
  // apply Highcharts Modules to this array
  return [ Highstock ];
}

@NgModule({
  providers: [
    { provide: HIGHCHARTS_MODULES, useFactory: highchartsModules } // add as factory to your providers
  ]
})
export class AppModule { }
```

**Comment by cebor** [comment]
Initial Highstock & Highmaps support landed in `5.1.0`. https://github.com/cebor/angular-highcharts#highstock--highmaps-support

**Comment by moepkid** [comment]
I currently get an error while trying to use highstock. The module is as follows:

`import { NgModule } from '@angular/core';
import { UiModule } from '../ui.module';
import { SingleSensorChartHComponent } from './single-sensor-chart-H.component';
import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';

import * as highStock from 'highcharts/highstock';

@NgModule({
  imports: [
    UiModule,

    ChartModule,
  ],
  declarations: [
    SingleSensorChartHComponent
  ],
  providers: [
    {
      provide: HIGHCHARTS_MODULES,
      useFactory: highchartsModules
    },
  ],
  exports: [
    SingleSensorChartHComponent,

    ChartModule
  ]
})

export class MeteoChartsModule {

}

export function highchartsModules() {
  return [ highStock ];
}
`

The console says:

`TypeError: module is not a function
    at eval (webpack-internal:///../../../../angular-highcharts/angular-highcharts.es5.js:248)
    at Array.forEach (<anonymous>)
    at ChartService.initModules (webpack-internal:///../../../../angular-highcharts/angular-highcharts.es5.js:247)
    at new ChartModule (webpack-internal:///../../../../angular-highcharts/angular-highcharts.es5.js:277)
    at _createClass (webpack-internal:///../../../core/esm5/core.js:10817)
    at _createProviderInstance$1 (webpack-internal:///../../../core/esm5/core.js:10791)
    at initNgModule (webpack-internal:///../../../core/esm5/core.js:10744)
    at new NgModuleRef_ (webpack-internal:///../../../core/esm5/core.js:11987)
    at createNgModuleRef (webpack-internal:///../../../core/esm5/core.js:11977)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (webpack-internal:///../../../core/esm5/core.js:14287)`

**Comment by cebor** [comment]
@moepkid 
```ts
import highstock from 'highcharts/modules/stock.src'
```
this should work.

**Comment by moepkid** [comment]
@cebor Somehow it cant find the stock.src file. I instal;led highcharts trough npm.

**Comment by cebor** [comment]
highcharts version ?

**Comment by moepkid** [comment]
@cebor nvm, I was stupid. Forgot the .src.js. Thanks man for your hard work! The library is easy enough to understand :D

**Comment by moepkid** [comment]
@cebor somehow its still not working. The call new StockChart({}) initializes an object with only options in it. chart.ref returns undefined.

**Comment by cebor** [comment]
@moepkid  In which livecycle do you access `chart.ref`? Cause its only available after `ngAfterViewInit()`.

**Comment by moepkid** [comment]
@cebor I Think i found it. Maybe it is worth noting that the factory function and provider needs to be in the app.module and not a submodule. I now put that in app.module and the rest in the MeteoModule and it works! 

Also, Sorry if i screw up the formatting of the comments and code. Somehow the comment box can't translate my code to github code.

**Comment by epot** [comment]
Is there a working example with Highstock? Somehow I am getting similar issues than here, I must be missing something.

**Comment by moepkid** [comment]
@epot Just follow the instructions in the readme, but notice the following:

- Make sure the factory function and service call is in the main app.module.ts. 

- In the return array of the factory function, the structure is (if for example you want to use highstock) 
`return [exporting, highstock]`

importing 'exporting' and the other modules is done by 
`import <module_name> from 'highcharts/modules/<module_name>.src.js'` 
- notice that you may need to use '.js' after source.

**Comment by epot** [comment]
Oh I did not the .js in the readme, that must be the problem!

**Comment by epot** [comment]
Unfortunately it still does not work :(.

My app module looks like this:

    ...
    import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';
    import exporting from 'highcharts/modules/exporting.src.js';
    import highstock from 'highcharts/modules/stock.src.js';

    export function highchartsModules() {
        // apply Highstock Modules to this array
        return [ exporting, highstock ];
    }

    @NgModule({
        imports: [
            ...
            ChartModule
        ],
        declarations: [
            ...
        ],
        providers: [
            ...
        { provide: HIGHCHARTS_MODULES, useFactory: highchartsModules }
        ],
        bootstrap: [AppComponent]
    })
    export class AppModule { }

And I am getting this:
    
     Unhandled Promise rejection: module is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: module is not a function
        at angular-highcharts.es5.js:237
        at Array.forEach (<anonymous>)
        at ChartService.initModules (angular-highcharts.es5.js:236)
        at new ChartModule (angular-highcharts.es5.js:266)

**Comment by moepkid** [comment]
@epot which versions are you using for angular and the other librarieS?

**Comment by epot** [comment]
Angular 5.0.2, @types/highcharts 5.0.12 and angular-highcharts 5.1.1.

**Comment by moepkid** [comment]
@epot I think this is something specific for your project. Can you perhaps make a new empty project with only these libraries?

**Comment by cebor** [comment]
Working Example: https://stackblitz.com/edit/angular-uzdc1r

**Comment by epot** [comment]
Excellent, thank you both for your help!

**Comment by cebor** [comment]
@epot i think i got it. I accidently used `module` as a variable which is a keyword in nodejs.

Can you try version `5.1.2`?

**Comment by epot** [comment]
It looks like I got a different error now:

    zone.js?fad3:690 Unhandled Promise rejection: element is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: element is not a function
      at eval (eval at 85 (app.js:63),

**Comment by cebor** [comment]
nope it isn't

**Comment by epot** [comment]
Weird, any idea why it is still failing then? I can put a small repro on github if that helps.

**Comment by cebor** [comment]
@epot In this case `element` should be the reference to the Highcharts Module you are loading.

Maybe the import is incorrect or your angular starter is incompatible with this library.

**Comment by epot** [comment]
I am really not sure what is wrong, but I tested both with my complex project and a start project (https://github.com/preboot/angular-webpack.git) and I am getting the same error unfortunately :-/.
