### ISSUE TITLE
Exporting context menu is not being added to the stock chart

### ISSUE THREAD

**Issue by mneofit** [cebor/angular-highcharts#351]
Hi
I am trying to add the exporting menu to the stock chart using latest `angular-highcharts` and `highcharts`, but it is not adding. Using only highcharts 8.2.0 builds the context menu.

Dependencies:
`angular-highcharts`: 10.0.1
`highcharts`: 8.2.0
`angular`: 10.1

Sample with `angular-highcharts`: https://stackblitz.com/edit/angular-highcharts-stock-uvgsdc
Sample with `highcharts` only, with same configuration: https://stackblitz.com/edit/angular-highcharts-stock-cxnwua

**Comment by cebor** [comment]
fixed in latest release
