### ISSUE TITLE
How to use the ref$ observable to drillUp()?

### ISSUE THREAD

**Issue by AlexandrosG** [cebor/angular-highcharts#356]
Hi, I'm quite new to Angular and I am wondering how I can use the ref$ observable to drillUp() on my charts. 

I used to do `this.pieChart.ref.drillUp();` but since updating to Highcharts 7 and the latest angular-highcharts that supports 7, this no longer works.

I imported the drilldown module `import 'highcharts/modules/drilldown';` and now it seems to work but if ref is deprecated, how can I use the new observable to drillUp()?

**Comment by cebor** [comment]
fixed in the latest release
