### ISSUE TITLE
Problem with NPM v7 and angular 11

### ISSUE THREAD

**Issue by Rotzbua** [cebor/angular-highcharts#361]
## environment
angular: 11
npm: 7.5.6

## error message
```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.0.0" from angular-highcharts@11.2.2
npm ERR! node_modules/angular-highcharts
npm ERR!   angular-highcharts@"^11.2.2" from the root project
```

## problem

Dependency seems to be wrong/outdated.

## solution

Fix dependency.

## workaround

Use npm with `--legacy-peer-deps`.

**Comment by cebor** [comment]
fixed in 11.3.1
