### ISSUE TITLE
License

### ISSUE THREAD

**Issue by EsbenVitecsoftware** [cebor/angular-highcharts#363]
Your license is incorrect please update. If you go to the official web page it is definitely not MIT. Please update on npmjs as well.

**Comment by cebor** [comment]
Hi, this is just a wrapper and its not dependent on the official Highcharts Library, so i can choose my own License.

**Comment by EsbenVitecsoftware** [comment]
But it is a wrapper to a licensed library. At least state that somewhere.

**Comment by cebor** [comment]
Added it to the first line of my README.md

https://github.com/cebor/angular-highcharts/blob/master/README.md

**Comment by EsbenVitecsoftware** [comment]
Perfect.
