### ISSUE TITLE
StockChart doesn't contain getSVG() method

### ISSUE THREAD

**Issue by ValeriiMalkov** [cebor/angular-highcharts#373]
AppComponent:
```import { AppComponent } from './app.component';

import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';
import * as more from 'highcharts/highcharts-more.src';
import * as exporting from 'highcharts/modules/exporting.src';
import stock from 'highcharts/modules/stock.src';
@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, ChartModule],
  providers: [
    { provide: HIGHCHARTS_MODULES, useFactory: () => [exporting,more,  stock] },
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

Creating Chart:
```
chart = new StockChart({
    chart: {
      type: 'line',
      events: {
        load() {
          console.log(this)
        }
      }
    },
    title: {
      text: 'Linechart'
    },
    credits: {
      enabled: false
    },
    exporting: {
      enabled: true,
      allowHTML: true,
      
    },

    rangeSelector: {enabled: false},
    series: [
      {
        type:undefined,
        name: 'Line 1',
        data: [1, 2, 3]
      }
    ]
  });
```

After that chart object contain next propery:
```
ref,
ref$,
options,
refSubject
```

chart.ref should contain getSVG() method but it doesn't.
It is not reproduced if create new Chart() object.
How to solve this issue for StockChart?
```
"highcharts": "^8.2.2",
"angular-highcharts": "^11.3.1"
```

**Comment by ValeriiMalkov** [comment]
@cebor Please tell me how to fix this as soon as possible. It's a big problem for my project

**Comment by cebor** [comment]
Hi @ValeriiMalkov, just subscribe to the ref$. Then you should get back the highcharts ref as a value.

https://angular.io/guide/observables#subscribing

**Comment by ValeriiMalkov** [comment]
Hi @cebor ! Thanks for responding!
I've subscribed but getSBG() still not exist
```
this.chart = new StockChart({
      chart: {
        type: 'line',
        events: {
          load() {
            console.log(this)
          }
        }
      },
      title: {
        text: 'Linechart'
      },
      credits: {
        enabled: false
      },
      exporting: {
        enabled: true,
        allowHTML: true,
        
      },
  
      rangeSelector: {enabled: false},
      series: [
        {
          type:undefined,
          name: 'Line 1',
          data: [1, 2, 3]
        }
      ]
    });
    const myObserver = {
      next: (x: number) => console.log('Observer got a next value: ' + x),
      error: (err: Error) => console.error('Observer got an error: ' + err),
      complete: () => console.log('Observer got a complete notification'),
    };
    this.chart.ref$.subscribe((d) => {
      console.log(d)
    })
```

**Comment by cebor** [comment]
Ok, it seems that the `export` module is not properly loaded. Do you see the menu to export a chart in the gui? Maybe you have to do it manually, atm module loading is only supported for normal Highcharts.

**Comment by ValeriiMalkov** [comment]
> Ok, it seems that the `export` module is not properly loaded. Do you see the menu to export a chart in the gui? Maybe you have to do it manually, atm integrated module loading is only supported for normal Highcharts.
@cebor 
No, i dont see menu to export. I see menu export if i create Chart instance instead of StockChart. In the Chart instance the group methods for export are exist what i cant say about StockChart.

What could be the solution for me? I need to export multiple stockcharts into pdf document

**Comment by cebor** [comment]
Should be fixed in the latest version..
