### ISSUE TITLE
Angular 16 Compatibility - Error

### ISSUE THREAD

**Issue by DaniSix** [cebor/angular-highcharts#391]
I would like to know what estimated date you have to launch the version compatible with Angular 16
Thanks

**Comment by leifjones** [comment]
To elaborate on our use case, we're working to to upgrade our application to Angular 16. We've already updated several dependencies in consort but now this one is blocking us. (Because we use Renovate, we can't have it include the `--force` tag so that suggestion below is a non-starter.)

After updating our application to 16, `npm install` is now blocked by the following error:

```bash
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: angular-highcharts@15.0.1
npm ERR! Found: @angular/common@16.0.4
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"16.0.4" from the root project
npm ERR!   peer @angular/common@"^15.0.0 || ^16.0.0" from @angular/cdk@15.1.2
npm ERR!   node_modules/@angular/cdk
npm ERR!     @angular/cdk@"^15.1.2" from the root project
npm ERR!   12 more (@angular/forms, @angular/platform-browser, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^15.1.1" from angular-highcharts@15.0.1
npm ERR! node_modules/angular-highcharts
npm ERR!   angular-highcharts@"^15.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@15.2.9
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^15.1.1" from angular-highcharts@15.0.1
npm ERR!   node_modules/angular-highcharts
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by bhiapp4** [comment]
We are also waiting for Angular 16 compatible version of this. Could you please update it to Angular 16 ?

**Comment by leifjones** [comment]
And/or does anyone know of a pattern for using highcharts directly in Angular without this package. We currently use it for its Chart import

**Comment by bhiapp4** [comment]
looks like there is official highcharts angular wrapper library from high charts itself https://github.com/highcharts/highcharts-angular

**Comment by leifjones** [comment]
> looks like there is official highcharts angular wrapper library from high charts itself https://github.com/highcharts/highcharts-angular

Has anyone done a migration from this package to highchart's package listed above?

**Comment by leifjones** [comment]
> we have forked and updated angular dependencies, but we would like to have the author create a new version

@DaniSix Could you maybe publish a PR for this? (I was working on a branch for that, but didn't get around to resolving all the issues.)
