### ISSUE TITLE
Support for Angular v17

### ISSUE THREAD

**Issue by torkilp** [cebor/angular-highcharts#394]
Support for Angular v17 thanks

**Comment by sameendraK** [comment]
Hello torkilp,
I'm trying to help you but I am unable to understand your problem.
Can you please describle it more clearly?

**Comment by torkilp** [comment]
Hi sameendraK
Shortly it was to have a version of Angular HighCharts which is supporting
Angular V17.

**Comment by torkilp** [comment]
Thanks a lot:-);
