### ISSUE TITLE
highcharts more / remove series?

### ISSUE THREAD

**Issue by bona1337** [cebor/angular-highcharts#4]
hello,

well I've tried some different highcharts wrapper but this is definitly my favourite one! 
The last things I'm really missing is the option to display no data available (comming from the highcharts-more) and to be able to remove a series... is this on your roadmap in mind?

would love to have those options! 👍

**Comment by cebor** [comment]
Question 1: 
What do you mean with "display no data available" have you an example for that ?

Question 2:
Removing charts directly via the `Chart` object is definitely on my roadmap, but for now you can use the native highcharts api accessible via `yourChart.ref`.

For example
```javascript
// removes serie at index 0
yourChart.ref.series[0].remove(true)
```
Offical Docs: http://api.highcharts.com/highcharts#Series.remove

**Comment by bona1337** [comment]
There is an extra module from highcharts...
here's a fiddle..
http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/no-data-to-display/no-data-pie/

great! thanks a lot :-)

**Comment by cebor** [comment]
@bona1337 

If you are using webpack or SystemJs you should be able to get highcharts plugins working, as described here: http://www.highcharts.com/docs/getting-started/install-from-npm

**Comment by cebor** [comment]
I'm planing to build this directly into the directive ...

**Comment by cebor** [comment]
I will release a fix tonight, which exports `Highcharts`, so you can import it and apply any extra module.

**Comment by cebor** [comment]
Landed in: https://github.com/cebor/angular-highcharts/commit/fb1942b72c4d94ec732ebb30122c6f6b212f242f

https://github.com/cebor/angular-highcharts/commit/fb1942b72c4d94ec732ebb30122c6f6b212f242f

**Comment by cebor** [comment]
In your case just add the following: 

```typescript
import { Highcharts } from 'angular-highcharts';
require('highcharts/modules/no-data-to-display')(Highcharts);
```

**Comment by bona1337** [comment]
thanks man! super awesome!!! 👍
