### ISSUE TITLE
I had no issues with this library. Great job!

### ISSUE THREAD

**Issue by AckerApple** [cebor/angular-highcharts#54]
Close this report when you want. Not an issue.

I researched 3 main libraries on NPM. After careful examination I choose this library and I'm certain it was the right choice.

Other Libraries
- Had issues that had not been addressed in quite some time
- Had no updates in months
- Didn't have the best looking ngOnDestroy aka clean-up code
- Had poor documentation

I really like this library. Five thumbs up. Great job!

**Comment by cebor** [comment]
Thank you very much! :)
