### ISSUE TITLE
Implementation of highcharts.destroy() and highcharts.update() functions

### ISSUE THREAD

**Issue by fervanrijswijk** [cebor/angular-highcharts#56]
Highcharts has functions to update and destroy a chart. When data changes every few seconds, the chart can be updated instead of created over and over again without the ability of being destroyed. 

I would like to be able to do one of the things below to prevent memory leaks.

```typescript
private createHighchart (options: HighchartOptions): void {
    if(this.chart) {
      this.chart.update(options);
    }
    else {
      this.chart = new Highchart(options);
    }
  }
```
```typescript
private createHighchart (options: HighchartOptions): void {
    if(this.chart) {
      this.chart.destroy();
    }
    else {
      this.chart = new Highchart(options);
    }
  }
```

**Comment by cebor** [comment]
@fervanrijswijk its possible: try to use `this.chart.ref`. This is a reference to the original highcharts object.

**Comment by fervanrijswijk** [comment]
Thanks!
