### ISSUE TITLE
Unhandled promise

### ISSUE THREAD

**Issue by kwaggarsa** [cebor/angular-highcharts#57]
I used your code exaclty, it compiles but once you run it i get the following error:
Could anyone perhaps help ?

zone.js:642 Unhandled Promise rejection: Template parse errors:
Can't bind to 'chart' since it isn't a known property of 'div'. ("
  </div>
  <button (click)="add()">Add Point</button>
  <div [ERROR ->][chart]="chart"></div>
  
</div>"): ng:///graphModule/graphComponent.html@5:7 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:

**Comment by cebor** [comment]
@kwaggarsa can you please create a sample repo or plunkr to reproduce this ?

**Comment by attilacsanyi** [comment]
`"Can't bind to 'chart' since it isn't a known property of 'div'"` is a common general error in angular if you forgot to [import](https://github.com/cebor/angular-highcharts#usage-example) the `ChartModule` in your app module or not included in your feature module. @kwaggarsa

**Comment by kwaggarsa** [comment]
Sorry Guys, I did a npm update and now I first have to fix all the errors.
