### ISSUE TITLE
boxplot chart is not working

### ISSUE THREAD

**Issue by prashuMishra** [cebor/angular-highcharts#61]
I am trying to create boxplot chart. but it is throwing error.

Highcharts error #17: www.highcharts.com/errors/17
    at Object.a.error (highcharts.js:10)
    at a.Chart.initSeries ....

i have imported  chartmodule on my appcomponent:
     import { ChartModule } from 'angular-highcharts';
and Chartmodule injected into import array.

**Comment by cebor** [comment]
I think you have to load some extra stuff, see: https://github.com/cebor/angular-highcharts#using-highcharts-modules

**Comment by prashuMishra** [comment]
i have added the below three lines in my appmodule

import { Highcharts } from 'angular-highcharts';
import exporting from 'highcharts/modules/exporting.src.js';
exporting(Highcharts)

 now error is change "Cannot read property 'defaultOptions' of undefined
    at exporting.src.js:29"

**Comment by cebor** [comment]
You have to load the "more" or some other module.

But strange that the "exporting" module does not work.

**Comment by alextroto** [comment]
Same issue with guage.
I don't really understand how should I import highcharts-more.
  @prashuMishra : did u solve it?
Thx,
Alex

**Comment by prashuMishra** [comment]
Yes it has been resolved at my end..  below code may resolve your problem too.

declare var require: any;
const Highcharts = require('highcharts/highcharts');
const HighchartsMore = require('highcharts/highcharts-more');
HighchartsMore(Highcharts);

**Comment by alextroto** [comment]
Worked !
Thanks a lot @prashuMishra
