### ISSUE TITLE
visible property does not work inside series.

### ISSUE THREAD

**Issue by snaik2064** [cebor/angular-highcharts#63]
I am trying to use visible property inside series like:
```
 series: [{
        name: 'Tokyo',
        data: [49.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4],
        visible: false
    }]
```
The code works for simple highcharts not for angular-highcharts, whenever I try to implement it gives the following error:
```
Types of property 'series' are incompatible.
    Type '{ name: string; data: number[]; visible: boolean; }[]' is not assignable to type 'IndividualSeriesOptions[]'.
      Type '{ name: string; data: number[]; visible: boolean; }' is not assignable to type 'IndividualSeriesOptions'.
        Object literal may only specify known properties, and 'visible' does not exist in type 'IndividualSeriesOptions'. 
```

**Comment by cebor** [comment]
This is a typing problem with @types/highcharts, nothing i can do here.

**Comment by snaik2064** [comment]
So @cebor  can you please suggest any way (property) in "angular-highcharts" with which I can hide only  a particular data from series ?
 
Like we do in normal high-charts:
http://jsfiddle.net/5u6oas2t/
