### ISSUE TITLE
Drill down is not working for angular-highcharts

### ISSUE THREAD

**Issue by GauravNagpure** [cebor/angular-highcharts#64]
I was trying to use pie chart to pie chart drilldown, but it looks like it has used in highchart.js but not implemented in this package. 

https://www.highcharts.com/demo/pie-drilldown
I am looking for exact same feature as given in above link.
Can you please help me with that ?
Thanks

**Comment by cebor** [comment]
@GauravNagpure you have to loade some extra modules: see https://github.com/cebor/angular-highcharts#using-highcharts-modules

**Comment by GauravNagpure** [comment]
@cebor I have imported Highcharts and drilldown as instructed in https://github.com/cebor/angular-highcharts#using-highcharts-modules, like this,
```
import { Highcharts } from 'angular-highcharts';
import drilldown from 'highcharts/modules/drilldown.src.js';
drilldown(Highcharts)
```
after calling drilldown function getting following error.
```
Uncaught TypeError: Cannot read property 'noop' of undefined
    at drilldown.src.js:27
    at drilldown.src.js:1017
```
Highcharts object is seems to be undefined which is imported from 'angular-highcharts'.

**Comment by gaurishrane** [comment]
I am also facing the same issue try with importing but not able to get the result.
Please anyone has a solution on this.

**Comment by Franky238** [comment]
Same issue... Highcharts undefined

**Comment by Sathiesh-Cango** [comment]
@cebor I'm also facing the same issue which @GauravNagpure facing. Please help us to solve this issue as soon as. Thanks in advance

**Comment by Franky238** [comment]
@Sathiesh-Cango try my solution
```
import Highcharts from 'highcharts';
import drilldown from 'highcharts/modules/drilldown.src.js';
drilldown(Highcharts)
```

Because `Highcharts` is `undefined`  from this library. Try to import it directly from highcharts library. (Be careful it is without `{}`

**Comment by Sathiesh-Cango** [comment]
Thanks @Franky238, drilldown function is working.
And I have one more double how to import 3D charts

**Comment by Franky238** [comment]
``` ts
import highcharts3D from 'highcharts/js/highcharts-3d.src.js'
```

**Comment by Sathiesh-Cango** [comment]
I'm also not able to load the area charts. 
I used `type: 'arearange',`

**Comment by Sathiesh-Cango** [comment]
@Franky238 I imported this for 3d effect `import highcharts3D from 'highcharts/js/highcharts-3d.src.js'`, but it is not working. help me...

**Comment by Franky238** [comment]
so you need to call it like 
```
highcharts3D (Highcharts);
```

**Comment by cebor** [comment]
Hello, i recommend follwoing way to import the `highcharts` ref:

```ts
import * as Highcharts from 'highcharts';
import drilldown from 'highcharts/modules/drilldown.src.js';
drilldown(Highcharts)
```

**Comment by Franky238** [comment]
@cebor true story... tslint error because highcharts has no default export

**Comment by Sathiesh-Cango** [comment]
@Franky238 I tried like below
`import drilldown from 'highcharts/modules/drilldown.src.js';
import highcharts3D from 'highcharts/js/highcharts-3d.src.js';
drilldown(Highcharts);
highcharts3D(Highcharts)`

while executing I got an error as 

> 
> DashboardComponent.html:8 ERROR TypeError: this.definition is not a function
>     at a.SVGRenderer.<anonymous> (http://localhost:4200/vendor.bundle.js:4281:22)
>     at Array.forEach (<anonymous>)
>     at a.each (http://localhost:4200/vendor.bundle.js:3680:325)
>     at a.SVGRenderer.<anonymous> (http://localhost:4200/vendor.bundle.js:4274:13)
>     at a.SVGRenderer.a.(anonymous function) [as init] (http://localhost:4200/vendor.bundle.js:3671:186)
>     at new a.SVGRenderer (http://localhost:4200/vendor.bundle.js:3713:378)
>     at a.Chart.getContainer (http://localhost:4200/vendor.bundle.js:3891:309)
>     at a.Chart.<anonymous> (http://localhost:4200/vendor.bundle.js:5499:21)
>     at a.Chart.a.(anonymous function) [as getContainer] (http://localhost:4200/vendor.bundle.js:3671:186)
>     at a.Chart.firstRender (http://localhost:4200/vendor.bundle.js:3905:431)

Please help

**Comment by Franky238** [comment]
@Sathiesh-Cango hard question. In my case it is working.

**Comment by Sathiesh-Cango** [comment]
Hi @Franky238 now 3D working. I imported as 
`import highcharts3D from 'highcharts/highcharts-3d.src.js';`
'highcharts3D(Highcharts)`
Thanks for the initial Support

**Comment by Sathiesh-Cango** [comment]
I'm also not able to load the area charts.
I used type: 'arearange',

**Comment by GauravNagpure** [comment]
`import * as Highcharts from 'highcharts';
import drilldown from 'highcharts/modules/drilldown.src.js';
drilldown(Highcharts)`
this code works for me. Thanks @cebor

**Comment by cebor** [comment]
This is the "new way" to import Highchartsmodules: https://github.com/cebor/angular-highcharts/releases/tag/v4.0.0

**Comment by Sathiesh-Cango** [comment]
@cebor I tried to import as per v4.0.0 and also I updated in package.json for angular-highcharts to ^4.0.0 but I get an error while importing as 

> node_modules/angular-highcharts/angular-highcharts"' has no exported member 'HighchartsModule'.

is there need to do any more configuration?
![screenshot from 2017-10-16 17-54-53](https://user-images.githubusercontent.com/32829187/31612007-ee6eaa98-b29b-11e7-84bd-1ef608b2027c.png)

**Comment by Franky238** [comment]
you need register provider... read readme file propertly
```ts
@NgModule({
  providers: [
    { provide: HIGHCHARTS_MODULES, useValue: [exporting] } // apply Highcharts Modules
  ]
})
```

**Comment by Sathiesh-Cango** [comment]
@Franky238  I did that too but importing itself occurring error. so providers also showing error

//registering in provider
![screenshot from 2017-10-16 18-06-13](https://user-images.githubusercontent.com/32829187/31612244-bc1d1f10-b29c-11e7-9e5d-901cc51b7b22.png)

**Comment by cebor** [comment]
@Sathiesh-Cango 
```
rm -r node_modules && npm i
```

**Comment by Sathiesh-Cango** [comment]
@cebor I did the above command, the same error occurs.

**Comment by cebor** [comment]
@Sathiesh-Cango try to update to `4.0.1` this should fix your issues

**Comment by Sathiesh-Cango** [comment]
@cebor  I updated to 4.0.1
![screenshot from 2017-10-16 19-05-59](https://user-images.githubusercontent.com/32829187/31614764-17c8d888-b2a5-11e7-9b33-437cd597d324.png)

Eventhough I'm facing problem while running the ng serve itself
> node_modules/angular-highcharts/chart.d.ts (1,1): Cannot find type definition file for 'highcharts'.

**Comment by cebor** [comment]
1. npm i -D @types/highcharts.
2. There was an issue with AOT compiler
```ts
// try this
import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';
import exporting from 'highcharts/modules/exporting.src.js';

export function highchartsModules() {
  // apply Highcharts Modules to this array
  return [ exporting ];
}

@NgModule({
  providers: [
    { provide: HIGHCHARTS_MODULES, useFactory: highchartsModules } // add as factory to your providers
  ]
})
```

**Comment by Sathiesh-Cango** [comment]
@cebor I tried with above guidelines, now I'm facing error while starting the `ng serve` as

> node_modules/@types/highcharts/index"' has no default export.

**Comment by cebor** [comment]
@Sathiesh-Cango for me this looks you are using `4.0.0` not `4.0.1`.

Try to clean npm/yarn caches, remove `node_modules`, `yarn.lock`, `package-lock.json`.

**Comment by Sathiesh-Cango** [comment]
Thanks @cebor now the errors are solved but I don't know the difference of previously we used and currently we because in component I'm imporing `import * as Highcharts from 'highcharts';`. 
Similarly 
`import drilldown from 'highcharts/modules/drilldown.src.js';`
`import highcharts3D from 'highcharts/highcharts-3d.src.js';`
`drilldown(Highcharts);`
`highcharts3D(Highcharts);` 

So I don't know what is the benefits of it.
