### ISSUE TITLE
solid-gauge chart

### ISSUE THREAD

**Issue by cunla** [cebor/angular-highcharts#65]
How can I include solid-gauge chart? I tried using the solution mention to include exporting but it does not work.
I am working with ionic 3.6.1

**Comment by cunla** [comment]
Eventually solved like this: in app.module.ts:
```
import solidgauge from 'highcharts/modules/solid-gauge';
import more from 'highcharts/highcharts-more';
import * as Highcharts from 'highcharts';
more(Highcharts);
solidgauge(Highcharts);
```

**Comment by yeomann** [comment]
so that mean, Angular Highchart doesn't contain solid gauge and more....

**Comment by cebor** [comment]
@yeomann solid gauge should work, just import the correct module.

https://github.com/cebor/angular-highcharts#using-highcharts-modules

**Comment by yeomann** [comment]
well i was not able to do with latest Ionic 3+ and Angualr 5+ so i am using just highcharts.js no other wrappers around it for ts
