### ISSUE TITLE
Missing responsive.plotOptions supports?

### ISSUE THREAD

**Issue by brandy253** [cebor/angular-highcharts#68]
Hi,

I am looking for the plotOptions inside the responsive property, but I cannot find it? Is it supported within the library?

```
this.chart = new Chart({
      chart: {
        type: 'line'
      },      
      series: [{
        name: 'Line 1',
        data: [1, 2, 3]
      }],
      responsive: [{
        rules: [{
          condition: {
            maxWidth: 1000
          },
          chartOptions: {
            plotOptions: {        //  Syntax error here, plotOptions cannot be found

            }
          }
        }]
      }]
    });
```

Please help, thanks for the awesome wrapper btw :)

**Comment by jarrettj** [comment]
I don't think so. Looking for it as well. Did you get it to work?

**Comment by cebor** [comment]
This is a problem with `@types/highcharts`.

As workorung follow the guidelines mentioned in the troubleshooting section: https://github.com/cebor/angular-highcharts#troubleshooting

**Comment by jarrettj** [comment]
Thanks. Will give it a try. Regards, JJ
