### ISSUE TITLE
Highchart modules

### ISSUE THREAD

**Issue by Hesesses** [cebor/angular-highcharts#75]
Hello and thank you for this great library!

I'm trying to use highchart modules, but cant get any of those to work.

I have this on my sharedmodule
```
import { ChartModule, Highcharts } from 'angular-highcharts';
import exporting from 'highcharts/modules/exporting.src.js';
exporting(Highcharts);
```
And getting this error: `Uncaught TypeError: Cannot read property 'defaultOptions' of undefined
    at exporting.src.js:29`

Any ideas? 

```
ng -v
@angular/cli: 1.4.4
node: 7.8.0
os: darwin x64
@angular/animations: 4.4.4
@angular/common: 4.4.4
@angular/compiler: 4.4.4
@angular/core: 4.4.4
@angular/forms: 4.4.4
@angular/http: 4.4.4
@angular/platform-browser: 4.4.4
@angular/platform-browser-dynamic: 4.4.4
@angular/router: 4.4.4
@angular/cli: 1.4.4
@angular/compiler-cli: 4.4.4
typescript: 2.2.2
```

**Comment by cebor** [comment]
See: https://github.com/cebor/angular-highcharts/releases/tag/v4.0.0

**Comment by Janatbek** [comment]
@cebor I was able to import modules as you explained in the link. 
Treemap works with imports of heatmap and treemap from highcharts/modules.

But, how can I ```import highcharts-more from "highcharts/highcharts-more.src.js"``` to use it with boxplots and scatterplots? 
Typescript throws an error: 
``` javascript
[ts] Cannot find name more

[ts] ';' expected.
[ts] Cannot find name 'from'.
```

**Comment by cebor** [comment]
@Janatbek please show me more of your code, can't reproduce the error.

**Comment by Janatbek** [comment]
Can I create a repository and show you what I am trying to do?

**Comment by Janatbek** [comment]
I need to import highcharts-more in order to render boxplot, and highcharts-more has hyphen that typescript complains about it, 
when I hover over the red underline it says 
```
[ts] Cannot find name more

[ts] ';' expected.
[ts] Cannot find name 'from'.

```
The error: 
![capture1](https://user-images.githubusercontent.com/16279325/31788033-b8e1535e-b4ca-11e7-9e08-b03e348e32b7.PNG)


Te code: 
![capture](https://user-images.githubusercontent.com/16279325/31787970-7fbea054-b4ca-11e7-8fa4-7080b2b8a821.PNG)

**Comment by cebor** [comment]
@Janatbek check the `-` in your variable name :)

**Comment by Janatbek** [comment]
I know, so How do I import variable name with hyphen sign?

**Comment by cebor** [comment]
nope, just rename it

**Comment by Janatbek** [comment]
LIke this:?
```
import highchartsMore from 'highcharts/highcharts-more.src.js';

export function highchartsModules() {
  // apply Highcharts Modules to this array
  return [ exporting, heatmap, treemap, highchartsMore ];
}
```
and I will have highcharts-more available for me?

**Comment by cebor** [comment]
yes, thats it

**Comment by Janatbek** [comment]
Thank you. It worked.

**Comment by vivianbirungi** [comment]
ERROR in ./node_modules/angular-highcharts/angular-highcharts.es5.js
Module not found: Error: Can't resolve 'highcharts' in 'C:\Users\DELL\Desktop\Apps\imuka\node_modules\angular-highcharts'

import * as Highcharts from 'highcharts';
