### ISSUE TITLE
Error with webpack

### ISSUE THREAD

**Issue by epot** [cebor/angular-highcharts#77]
I am trying to use this awesome component with Webpack but have the following issue in the Chrome console:

    (...)node_modules\angular-highcharts\chart.d.ts
    (1,1): error TS2688: Cannot find type definition file for 'highcharts'.

Any idea what I could be doing wrong?

**Comment by epot** [comment]
It seems to start working if I install @types/highcharts. As it was optional I did not do it before. You can close it if you want, but maybe the doc could be enhanced?

**Comment by cebor** [comment]
added to docs
