### ISSUE TITLE
Dynamically update title?

### ISSUE THREAD

**Issue by epot** [cebor/angular-highcharts#79]
I am trying to do something like:

    this.charts.options.title.text = this.currentDate.toDateString();

But the title does not get updated. Is there a way to "refresh" the highcharts below even if the data did not change?

**Comment by cebor** [comment]
Hi, can you try the following:

```ts
this.chart.reg.setTitle('New Title');
```

See: https://api.highcharts.com/class-reference/Highcharts.Chart#setTitle

**Comment by epot** [comment]
I guess you mean:

        this.charts.ref.setTitle({text: 'New Title'});

Unfortunately it seems this.charts.ref is undefined.

**Comment by cebor** [comment]
@epot `ref` should be defined after chart was initialized.

**Comment by epot** [comment]
Weird, it is definitely not defined on my side :-/.

**Comment by cebor** [comment]
@epot can you post some code to make this a little bit more reproducible

**Comment by cebor** [comment]
have you tried to use it inside `ngAfterViewInit` lifecycle ?

**Comment by epot** [comment]
Oops sorry I forgot to answer here. No, that is probably the issue, I can close this. Thanks!!
