### ISSUE TITLE
ColumnRange chart is not working.

### ISSUE THREAD

**Issue by yaashaswi** [cebor/angular-highcharts#81]
I have tried to add ColumnRange chart but it's giving "Highcharts error #17: www.highcharts.com/errors/17" Error.

`chart: {
                type: 'columnrange',
                inverted: true
            },

            title: {
                text: 'Temperature variation by month'
            },

            subtitle: {
                text: 'Observed in Vik i Sogn, Norway'
            },

            xAxis: {
                categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
            },

            yAxis: {
                title: {
                    text: 'Temperature ( °C )'
                }
            },

            tooltip: {
                valueSuffix: '°C'
            },

            plotOptions: {
                columnrange: {
                    dataLabels: {
                        enabled: true,
                        formatter: function () {
                            return this.y + '°C';
                        }
                    }
                }
            },

            legend: {
                enabled: false
            },

            series: [{
                name: 'Temperatures',
                data: [
                    [-9.7, 9.4],
                    [-8.7, 6.5],
                    [-3.5, 9.4],
                    [-1.4, 19.9],
                    [0.0, 22.6],
                    [2.9, 29.5],
                    [9.2, 30.7],
                    [7.3, 26.5],
                    [4.4, 18.0],
                    [-3.1, 11.4],
                    [-5.2, 10.4],
                    [-13.5, 9.8]
                ]
            }]`

**Comment by cebor** [comment]
I think you need to import some extra modules. See: https://github.com/cebor/angular-highcharts#using-highcharts-modules

**Comment by mblum14** [comment]
I ran into the same problem. The "columnrange" chart type is defined in `highcharts-more.src.js` as opposed to under the `modules` directory.
you can import from `highcharts/highcharts-more.src`:
```typescript
// app.module.ts
// ....
import more from 'highcharts/highcharts-more.src';
```
and just follow the directions in the link @cebor referenced.

**Comment by keephacking** [comment]
@cebor  , columnrange not workinging in angular 6 . https://stackblitz.com/edit/angular-highcharts-columnrange.
