### ISSUE TITLE
Angular highchart new version point padding is not working in series.

### ISSUE THREAD

**Issue by kushthakkar08** [cebor/angular-highcharts#86]
In old angular highchart(version:3.7.0), it was working check bellow:
  series: [
                        {
                            //showInLegend: false,
                            name: 'Target',
                            color: '#FF0000',
                            data: diseaseAreaTargetData,
                            pointPadding: 0.3,
                            pointPlacement: -0.2
                        }, {
                            //showInLegend: false,
                            name: 'Actual',
                            color: '#8085e9',
                            data: diseaseAreaActualData,
                            pointPadding: 0.4,
                            pointPlacement: -0.2
                        }]
              ]
In new angular highchart(version:5.0.1), pointPadding and pointPlacement is not working.

**Comment by cebor** [comment]
@kushthakkar08 do you get runtime errors or compile errors, please post some logs?

**Comment by kushthakkar08** [comment]
No

**Comment by kushthakkar08** [comment]
Yes,
![image](https://user-images.githubusercontent.com/31927312/32325847-a3b92ec0-bff6-11e7-8f02-36bd9edb76e3.png)

**Comment by kushthakkar08** [comment]
@cebor this error shows at runtime. Check above pic.

**Comment by cebor** [comment]
@kushthakkar08 This is a TS compile error. The problem seems to come from package `@types/highcharts`. Please report the error there. 

But app should work, also with typing errors.

**Comment by kushthakkar08** [comment]
No its not working.

**Comment by kushthakkar08** [comment]
@cebor  can I uninstall the typings.

**Comment by cebor** [comment]
@kushthakkar08 try the following

```ts
chart = new Chart(<any>{ // options here })
```

This should fix all typing errors.

**Comment by kushthakkar08** [comment]
Yes, It fix. Thank you @cebor .

**Comment by cebor** [comment]
Added to README: https://github.com/cebor/angular-highcharts/blob/master/README.md#troubleshooting
