### ISSUE TITLE
ERROR in Metadata version mismatch for module

### ISSUE THREAD

**Issue by Derekjohnson277** [cebor/angular-highcharts#87]
I'm getting this error when using "ng serve" command with angular-cli. I have the lastest version of highcharts (6.0.2), angular0highcharts(5.0.3), and @types/highcharts(5.0.9).

I'm running on Windows 10, angular 4.0.0, and using Google Chrome.

`ERROR in Metadata version mismatch for module ..(my directory)/node_modules/angular-highcharts/angular-highcharts.d.ts, found version 4, expected 3`

**Comment by cebor** [comment]
ok seems, that v5 is not compatible with angular4, please use v4
