### ISSUE TITLE
Set language options

### ISSUE THREAD

**Issue by lenpino** [cebor/angular-highcharts#89]
How do I set lang. This code doesn't work:

  // Configuracion global de highcharts (definicion de idioma)
  Highcharts.setOptions({
   lang: {
      months: ["Enero", 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
      weekdays: ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'],
      shortMonths: [ 'Ene' , 'Feb' , 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
      loading: 'Cargando...',  
      exportButtonTitle: 'Exportar',  
      printButtonTitle: 'Importar',  
      rangeSelectorFrom: 'De',  
      rangeSelectorTo: 'A',  
      rangeSelectorZoom: 'Periodo',  
      downloadPNG: 'Descargar gráfica PNG',  
      downloadJPEG: 'Descargar gráfica JPEG',  
      downloadPDF: 'Descargar gráfica PDF',  
      downloadSVG: 'Descargar gráfica SVG',  
      printChart: 'Imprimir Gráfica', 
      decimalPoint: ',',
      thousandsSep: '.'
    }
    
  });

**Comment by cebor** [comment]
please provide some error or compile logs to make this reproducible?

**Comment by cebor** [comment]
Try to import Highcharts:

```ts
// v5
import { Highcharts } from 'angular-highcharts';

// v4
import * as Highcharts from 'highcharts'
```
