### ISSUE TITLE
Variwide 

### ISSUE THREAD

**Issue by nameisvick** [cebor/angular-highcharts#91]
Can any 1 tell me does highchart support variwide charts in angular program ? .. if it supports can any 1 tell me how to use it because giving  type: 'variwide' gives error in console like     ERROR Error: Highcharts error #17: www.highcharts.com/errors/17
Stack trace:
../../../../highcharts/highcharts.js/</</a.error@http://172.18.1.71:2000/5.chunk.js:2197:49
initSeries@http://172.18.1.71:2000/5.chunk.js:2418:45
firstRender/<@http://172.18.1.71:2000/5.chunk.js:2442:40
../../../../highcharts/highcharts.js/</</a.each@http://172.18.1.71:2000/5.chunk.js:2215:463
firstRender@http://172.18.1.71:2000/5.chunk.js:2442:13

https://www.npmjs.com/package/angular2-highcharts
i used the above link to integrate in my pgm ... P.S line , pie charts are working fine using the above method ...

**Comment by cebor** [comment]
https://www.npmjs.com/package/angular2-highcharts is a different package.

This is `angular-highcharts`
