### ISSUE TITLE
about exporting select

### ISSUE THREAD

**Issue by superestze** [cebor/angular-highcharts#92]
I can use highchart to set the export button .
     
![image](https://user-images.githubusercontent.com/14367486/32478705-40a235e2-c3c1-11e7-8edf-dbae2da4fb1b.png)
   ref:https://code.hcharts.cn/highcharts/hhhhsu/1

but how can i use ng-highchart to set the exporting button? thanks

**Comment by cebor** [comment]
Try to import Highcharts:

```ts
// v5
import { Highcharts } from 'angular-highcharts';

// v4
import * as Highcharts from 'highcharts'
```

**Comment by cebor** [comment]
Closing this, feel free to reopen.
